'use strict';
exports.BattleLearnsets = {
	yddraig: {
		learnset: {
			inferno: ["7L1", "7L54"],
			outrage: ["7L1", "7L60"],
			tackle: ["7L1"],
			ember: ["7L1"],
			tailwhip: ["7L1"],
			twister: ["7L1"],
			endeavor: ["7L4"],
			defog: ["7L9"],
			headbutt: ["7L13"],
			aircutter: ["7L18"],
			dragonbreath: ["7L22"],
			roar: ["7L27"],
			flamecharge: ["7L31", "7M"],
			dragondance: ["7L36"],
			boomburst: ["7L40"],
			dragonrush: ["7L45"],
			doubleteam: ["7L49", "7M"],
			clangingscales: ["7E"],
			dragonpulse: ["7E"],
			wideguard: ["7E"],
			overheat: ["7E", "7M"],
			dracometeor: ["7T"],
			workup: ["7M"],
			dragonclaw: ["7M"],
			calmmind: ["7M"],
			roar: ["7M"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			brickbreak: ["7M"],
			reflect: ["7M"],
			flamethrower: ["7M"],
			fireblast: ["7M"],
			aerialace: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			steelwing: ["7M"],
			roost: ["7M"],
			skydrop: ["7M"],
			brutalswing: ["7M"],
			acrobatics: ["7M"],
			shadowclaw: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			thunderwave: ["7M"],
			swordsdance: ["7M"],
			fly: ["7M"],
			bulldoze: ["7M"],
			dragontail: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			wildcharge: ["7M"],
			snarl: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	detuoy: {
		learnset: {
			explosion: ["7L1"],
		}
	},
	mycelore: {
		learnset: {
			acid: ["7L1"],
			fairywind: ["7L1"],
			absorb: ["7L4"],
			leechseed: ["7L7"],
			sludge: ["7L12"],
			ingrain: ["7L15"],
			megadrain: ["7L18"],
			acidspray: ["7L23"],
			toxic: ["7L26"],
			gigadrain: ["7L29"],
			toxicspikes: ["7L34"],
			moonblast: ["7L37"],
			venomdrench: ["7L40"],
			spore: ["7L45"],
			acidarmor: ["7E"],
			mistyterrain: ["7E"],
			aromatherapy: ["7E"],
			dazzlinggleam: ["7E", "7M"],
			aromaticmist: ["7E"],
			moonlight: ["7E"],
			calmmind: ["7M"],
			toxic: ["7M"],
			venoshock: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			sludgewave: ["7M"],
			sludgebomb: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			energyball: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			dreameater: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	muceptio: {
		learnset: {
			acid: ["7L1"],
			fairywind: ["7L1"],
			absorb: ["7L4"],
			leechseed: ["7L9"],
			sludge: ["7L14"],
			ingrain: ["7L17"],
			megadrain: ["7L22"],
			acidspray: ["7L27"],
			toxic: ["7L30"],
			gigadrain: ["7L35"],
			toxicspikes: ["7L40"],
			moonblast: ["7L43"],
			venomdrench: ["7L48"],
			spore: ["7L53"],
			acidarmor: ["7E"],
			mistyterrain: ["7E"],
			aromatherapy: ["7E"],
			dazzlinggleam: ["7E", "7M"],
			aromaticmist: ["7E"],
			moonlight: ["7E"],
			calmmind: ["7M"],
			toxic: ["7M"],
			venoshock: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			sludgewave: ["7M"],
			sludgebomb: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			energyball: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			dreameater: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	malifery: {
		learnset: {
			fairywind: ["7L1"],
			sludge: ["7L1"],
			moonblast: ["7L1"],
			spore: ["7L1"],
			acidarmor: ["7E"],
			mistyterrain: ["7E"],
			aromatherapy: ["7E"],
			dazzlinggleam: ["7E", "7M"],
			aromaticmist: ["7L1", "7E"],
			moonlight: ["7L1", "7E"],
			calmmind: ["7M"],
			toxic: ["7M"],
			venoshock: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			sludgewave: ["7M"],
			sludgebomb: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			energyball: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			dreameater: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			hyperbeam: ["7M"],
			gigaimpact: ["7M"],
		}
	},
	narwander: {
		learnset: {
			brine: ["7L1"],
			hornattack: ["7L1"],
			peck: ["7L5"],
			rocksmash: ["7L8"],
			watersport: ["7L11"],
			furyattack: ["7L14"],
			aquajet: ["7L17"],
			rapidspin: ["7L20"],
			drillrun: ["7L26"],
			megahorn: ["7L32"],
			lockon: ["7L38"],
			rotarydrill: ["7L44"],
			horndrill: ["7L50"],
			encore: ["7E"],
			soak: ["7E"],
			spikes: ["7E"],
			powertrip: ["7E"],
			heavyslam: ["7E"],
			iciclecrash: ["7E"],
			roar: ["7M"],
			toxic: ["7M"],
			hail: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			frustration: ["7M"],
			return: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			focusblast: ["7M"],
			falseswipe: ["7M"],
			scald: ["7M"],
			brutalswing: ["7M"],
			smartstrike: ["7M"],
			gyroball: ["7M"],
			swordsdance: ["7M"],
			frostbreath: ["7M"],
			xscissor: ["7M"],
			poisonjab: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			surf: ["7M"],
			waterfall: ["7M"],
			confide: ["7M"],
		}
	},
	ortuska: {
		learnset: {
			doubleedge: ["7L1"],
			superpower: ["7L1"],
			outrage: ["7L1"],
			thrash: ["7L1"],
			brine: ["7L1"],
			hornattack: ["7L1"],
			smartstrike: ["7L2", "7M"],
			peck: ["7L5"],
			rocksmash: ["7L8"],
			watersport: ["7L11"],
			furyattack: ["7L14"],
			aquajet: ["7L17"],
			rapidspin: ["7L20"],
			drillrun: ["7L26"],
			megahorn: ["7L32"],
			lockon: ["7L38"],
			rotarydrill: ["7L44"],
			horndrill: ["7L50"],
			encore: ["7E"],
			soak: ["7E"],
			spikes: ["7E"],
			powertrip: ["7E"],
			heavyslam: ["7E"],
			iciclecrash: ["7E"],
			roar: ["7M"],
			toxic: ["7M"],
			hail: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			frustration: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			focusblast: ["7M"],
			falseswipe: ["7M"],
			scald: ["7M"],
			brutalswing: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			stoneedge: ["7M"],
			gyroball: ["7M"],
			swordsdance: ["7M"],
			bulldoze: ["7M"],
			frostbreath: ["7M"],
			rockslide: ["7M"],
			xscissor: ["7M"],
			poisonjab: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			surf: ["7M"],
			waterfall: ["7M"],
			confide: ["7M"],
		}
	},
	larvary: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			irondefense: ["7L1"],
		}
	},
	burnabee: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			foresight: ["7L1"],
			honeyblaze: ["7L2"],
			ember: ["7L6"],
			silverwind: ["7L11"],
			helpinghand: ["7L16"],
			flameburst: ["7L21"],
			ragepowder: ["7L26"],
			healpulse: ["7L31"],
			lunge: ["7L36"],
			burnup: ["7L41"],
			bugbuzz: ["7L46"],
			heatwave: ["7L51"],
			quiverdance: ["7L56"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			flamethrower: ["7M"],
			fireblast: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			overheat: ["7M"],
			steelwing: ["7M"],
			energyball: ["7M"],
			fling: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	freezabee: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			foresight: ["7L1"],
			honeychill: ["7L2"],
			icywind: ["7L6"],
			silverwind: ["7L11"],
			helpinghand: ["7L16"],
			aurorabeam: ["7L21"],
			ragepowder: ["7L26"],
			healpulse: ["7L31"],
			lunge: ["7L36"],
			freezedry: ["7L41"],
			bugbuzz: ["7L46"],
			sheercold: ["7L51"],
			quiverdance: ["7L56"],
			toxic: ["7M"],
			hail: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			steelwing: ["7M"],
			energyball: ["7M"],
			fling: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	parabee: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			foresight: ["7L1"],
			honeystun: ["7L2"],
			thundershock: ["7L6"],
			silverwind: ["7L11"],
			helpinghand: ["7L16"],
			electroball: ["7L21"],
			ragepowder: ["7L26"],
			healpulse: ["7L31"],
			lunge: ["7L36"],
			discharge: ["7L41"],
			bugbuzz: ["7L46"],
			zapcannon: ["7L51"],
			quiverdance: ["7L56"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			steelwing: ["7M"],
			energyball: ["7M"],
			fling: ["7M"],
			chargebeam: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			voltswitch: ["7M"],
			thunderwave: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			wildcharge: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	drowzabee: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			foresight: ["7L1"],
			honeytrance: ["7L2"],
			confusion: ["7L6"],
			silverwind: ["7L11"],
			helpinghand: ["7L16"],
			psybeam: ["7L21"],
			ragepowder: ["7L26"],
			healpulse: ["7L31"],
			lunge: ["7L36"],
			psychicterrain: ["7L41"],
			bugbuzz: ["7L46"],
			synchronoise: ["7L51"],
			quiverdance: ["7L56"],
			psyshock: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			psychic: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			steelwing: ["7M"],
			energyball: ["7M"],
			fling: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	toxabee: {
		learnset: {
			protect: ["7L1"],
			bugbite: ["7L1"],
			foresight: ["7L1"],
			honeyvirus: ["7L2"],
			poisonsting: ["7L6"],
			silverwind: ["7L11"],
			helpinghand: ["7L16"],
			venoshock: ["7L21", "7M"],
			ragepowder: ["7L26"],
			healpulse: ["7L31"],
			lunge: ["7L36"],
			venomdrench: ["7L41"],
			bugbuzz: ["7L46"],
			toxicspikes: ["7L51"],
			quiverdance: ["7L56"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			sludgewave: ["7M"],
			sludgebomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			steelwing: ["7M"],
			energyball: ["7M"],
			fling: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			smartstrike: ["7M"],
			gigaimpact: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	magnalith: {
		learnset: {
			extremespeed: ["7L1"],
			accelerock: ["7L1"],
			fissure: ["7L1"],
			zapcannon: ["7L1"],
			thundershock: ["7L1"],
			rocktomb: ["7L1"],
			doubleteam: ["7L1", "7M"],
			magnetrise: ["7L1"],
			razorwind: ["7L9"],
			stealthrock: ["7L17"],
			powergem: ["7L25"],
			electricterrain: ["7L33"],
			rockslide: ["7L41", "7M"],
			rockpolish: ["7L49", "7M"],
			voltswitch: ["7L57", "7M"],
			earthpower: ["7L65"],
			finalgambit: ["7L73"],
			rockwrecker: ["7L81"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			smackdown: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			focusblast: ["7M"],
			energyball: ["7M"],
			chargebeam: ["7M"],
			skydrop: ["7M"],
			brutalswing: ["7M"],
			acrobatics: ["7M"],
			embargo: ["7M"],
			explosion: ["7M"],
			payback: ["7M"],
			stoneedge: ["7M"],
			thunderwave: ["7M"],
			fly: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			trickroom: ["7M"],
			wildcharge: ["7M"],
			surf: ["7M"],
			confide: ["7M"],
		}
	},
	canos: {
		learnset: {
			tackle: ["7L1"],
			lick: ["7L1"],
			howl: ["7L3"],
			astonish: ["7L8"],
			odorsleuth: ["7L10"],
			bite: ["7L15"],
			charm: ["7L17"],
			boneclub: ["7L22"],
			confuseray: ["7L24"],
			crunch: ["7L29"],
			headbutt: ["7L31"],
			shadowclaw: ["7L36"],
			destinybond: ["7L38"],
			bonerush: ["7L43"],
			takedown: ["7L45"],
			roar: ["7L50"],
			gigaimpact: ["7L52"],
			babydolleyes: ["7E"],
			quickattack: ["7E"],
			scaryface: ["7E"],
			feintattack: ["7E"],
			lastresort: ["7E"],
			mudslap: ["7E"],
			shadowbone: ["7E"],
			workup: ["7M"],
			roar: ["7M"],
			toxic: ["7M"],
			hail: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			return: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			rocktomb: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			brutalswing: ["7M"],
			quash: ["7M"],
			shadowclaw: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			thunderwave: ["7M"],
			bulldoze: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			snarl: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
			}
		},
		mortos: {
			learnset: {
				tackle: ["7L1"],
				lick: ["7L1"],
				howl: ["7L3"],
				astonish: ["7L8"],
				odorsleuth: ["7L10"],
				bite: ["7L15"],
				charm: ["7L17"],
				boneclub: ["7L22"],
				confuseray: ["7L24"],
				crunch: ["7L29"],
				headbutt: ["7L31"],
				shadowclaw: ["7L36"],
				destinybond: ["7L38"],
				bonerush: ["7L43"],
				takedown: ["7L45"],
				roar: ["7L50"],
				gigaimpact: ["7L52"],
				babydolleyes: ["7E"],
				quickattack: ["7E"],
				scaryface: ["7E"],
				feintattack: ["7E"],
				lastresort: ["7E"],
				mudslap: ["7E"],
				shadowbone: ["7E", "7L2"],
				workup: ["7M"],
				roar: ["7M"],
				toxic: ["7M"],
				hail: ["7M"],
				hiddenpower: ["7M"],
				sunnyday: ["7M"],
				taunt: ["7M"],
				icebeam: ["7M"],
				blizzard: ["7M"],
				hyperbeam: ["7M"],
				protect: ["7M"],
				raindance: ["7M"],
				frustration: ["7M"],
				solarbeam: ["7M"],
				return: ["7M"],
				shadowball: ["7M"],
				doubleteam: ["7M"],
				rocktomb: ["7M"],
				torment: ["7M"],
				facade: ["7M"],
				rest: ["7M"],
				attract: ["7M"],
				thief: ["7M"],
				round: ["7M"],
				echoedvoice: ["7M"],
				brutalswing: ["7M"],
				quash: ["7M"],
				shadowclaw: ["7M"],
				payback: ["7M"],
				gigaimpact: ["7M"],
				thunderwave: ["7M"],
				bulldoze: ["7M"],
				swagger: ["7M"],
				sleeptalk: ["7M"],
				substitute: ["7M"],
				trickroom: ["7M"],
				snarl: ["7M"],
				naturepower: ["7M"],
				darkpulse: ["7M"],
				confide: ["7M"],
				}	
			},
	molaxy: {
		learnset: {
			mudslap: ["7L1"],
			odorsleuth: ["7L1"],
			confusion: ["7L1"],
			mudsport: ["7L1"],
			sandattack: ["7L7"],
			mudsport: ["7L8"],
			dig: ["7L14"],
			detect: ["7L15"],
			sandtomb: ["7L21"],
			magnitude: ["7L22"],
			futuresight: ["7L28"],
			burrow: ["7L29"],
			psychic: ["7L35"],
			cosmicpower: ["7L36"],
			earthpower: ["7L42"],
			earthquake: ["7L43"],
			healblock: ["7L49"],
			fissure: ["7L50"],
			confuseray: ["7E"],
			psywave: ["7E"],
			moonlight: ["7E"],
			rototiller: ["7E"],
			synchronoise: ["7E"],
			psyshock: ["7E", "7M"],
			calmmind: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			echoedvoice: ["7M"],
			bulldoze: ["7M"],
			rockslide: ["7M"],
			infestation: ["7M"],
			dreameater: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			naturepower: ["7M"],
			confide: ["7M"],
		}
	},
	panoir: {
		learnset: {
			peck: ["7L1"],
			astonish: ["7L1"],
			quickattack: ["7L5"],
			smackdown: ["7L8", "7M"],
			wideguard: ["7L13"],
			mirrormove: ["7L16"],
			wingattack: ["7L20"],
			stealthrock: ["7L23"],
			rockpolish: ["7L28", "7M"],
			rockslide: ["7L31", "7M"],
			roost: ["7L35", "7M"],
			drillpeck: ["7L38"],
			featherdance: ["7L43"],
			skyattack: ["7L46"],
			bravebird: ["7E"],
			agility: ["7E"],
			detect: ["7E"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			protect: ["7M"],
			frustration: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			doubleteam: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			steelwing: ["7M"],
			skydrop: ["7M"],
			acrobatics: ["7M"],
			explosion: ["7M"],
			payback: ["7M"],
			stoneedge: ["7M"],
			fly: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			confide: ["7M"],
		}
	},
	warkoal: {
		learnset: {
			peck: ["7L1"],
			astonish: ["7L1"],
			quickattack: ["7L5"],
			smackdown: ["7L9", "7M"],
			wideguard: ["7L14"],
			mirrormove: ["7L17"],
			wingattack: ["7L21"],
			stealthrock: ["7L25"],
			rockpolish: ["7L30", "7M"],
			rockslide: ["7L33", "7M"],
			roost: ["7L37", "7M"],
			drillpeck: ["7L40"],
			featherdance: ["7L46"],
			skyattack: ["7L49"],
			bravebird: ["7E"],
			agility: ["7E"],
			detect: ["7E"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			protect: ["7M"],
			frustration: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			doubleteam: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			steelwing: ["7M"],
			skydrop: ["7M"],
			acrobatics: ["7M"],
			explosion: ["7M"],
			payback: ["7M"],
			stoneedge: ["7M"],
			fly: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			confide: ["7M"],
		}
	},
	frigalt: {
		learnset: {
			peck: ["7L1"],
			astonish: ["7L1"],
			rockrequite: ["7L2"],
			quickattack: ["7L5"],
			smackdown: ["7L9", "7M"],
			wideguard: ["7L13"],
			mirrormove: ["7L17"],
			wingattack: ["7L21"],
			stealthrock: ["7L25"],
			rockpolish: ["7L29", "7M"],
			rockslide: ["7L33", "7M"],
			roost: ["7L37", "7M"],
			drillpeck: ["7L41"],
			featherdance: ["7L45"],
			skyattack: ["7L49"],
			rockrequite: ["7L53"],
			bravebird: ["7E"],
			agility: ["7E"],
			detect: ["7E"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			protect: ["7M"],
			frustration: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			doubleteam: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			steelwing: ["7M"],
			skydrop: ["7M"],
			acrobatics: ["7M"],
			explosion: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			stoneedge: ["7M"],
			fly: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			confide: ["7M"],
		}
	},
	manakley: {
		learnset: {
			wideguard: ["7L1"],
			fling: ["7L1", "7E", "7M"],
			pound: ["7L4"],
			detect: ["7L10"],
			dizzypunch: ["7L16"],
			irondefense: ["7L22"],
			takedown: ["7L28"],
			drainpunch: ["7L34"],
			ironhead: ["7E"],
			retaliate: ["7E"],
			metalsound: ["7E"],
			entrainment: ["7E"],
			workup: ["7M"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			protect: ["7M"],
			frustration: ["7M"],
			smackdown: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			rocktomb: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			round: ["7M"],
			brutalswing: ["7M"],
			embargo: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			confide: ["7M"],
		}
	},
	maniakley: {
		learnset: {
			doubleedge: ["7L1"],
			revenge: ["7L1"],
			bulkup: ["7L1"],
			superpower: ["7L1"],
			wideguard: ["7L1"],
			fling: ["7L1", "7E", "7M"],
			shackleswing: ["7L2"],
			pound: ["7L5"],
			detect: ["7L12"],
			drainpunch: ["7L19"],
			irondefense: ["7L26"],
			takedown: ["7L33"],
			revenge: ["7L40"],
			block: ["7L47"],
			superpower: ["7L54"],
			metalburst: ["7L61"],
			ironhead: ["7E"],
			retaliate: ["7E"],
			metalsound: ["7E"],
			entrainment: ["7E"],
			workup: ["7M"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hiddenpower: ["7M"],
			protect: ["7M"],
			taunt: ["7M"],
			frustration: ["7M"],
			smackdown: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			earthquake: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			rocktomb: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			thief: ["7M"],
			lowsweep: ["7M"],
			round: ["7M"],
			focusblast: ["7M"],
			brutalswing: ["7M"],
			embargo: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			stoneedge: ["7M"],
			bulldoze: ["7M"],
			rockslide: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			snarl: ["7M"],
			confide: ["7M"],
		}
	},
	sparklet: {
		learnset: {
		}
	},
	spoark: {
		learnset: {
		}
	},
	spoarkwild: {
		learnset: {
		}
	},
	impite: {
		learnset: {
			quickattack: ["7L1"],
			doubleteam: ["7L1", "7M"],
			cometpunch: ["7L6"],
			lockon: ["7L12"],
			hiddenpower: ["7L15", "7M"],
			quickguard: ["7L19"],
			wideguard: ["7L19"],
			pursuit: ["7L24"],
			machpunch: ["7L27"],
			agility: ["7L31"],
			strength: ["7L36"],
			aurasphere: ["7L39"],
			meteorimpact: ["7L43"],
			endure: ["7L48"],
			closecombat: ["7L51"],
			megapunch: ["7L55"],
			superpower: ["7L60"],
			dynamicpunch: ["7E"],
			detect: ["7E"],
			thunderpunch: ["7E"],
			firepunch: ["7E"],
			icepunch: ["7E"],
			workup: ["7M"],
			toxic: ["7M"],
			bulkup: ["7M"],
			protect: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			smackdown: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			lowsweep: ["7M"],
			round: ["7M"],
			skydrop: ["7M"],
			acrobatics: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			rockpolish: ["7M"],
			stoneedge: ["7M"],
			thunderwave: ["7M"],
			fly: ["7M"],
			psychup: ["7M"],
			bulldoze: ["7M"],
			rockslide: ["7M"],
			poisonjab: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			dazzlinggleam: ["7M"],
			confide: ["7M"],
		}
	},
	pacteorite: {
		learnset: {
			endure: ["7L1"],
			cometpunch: ["7L1"],
			agility: ["7L1"],
			superpower: ["7L1"],
			meteorimpact: ["7L2"],
			dynamicpunch: ["7E"],
			detect: ["7E"],
			thunderpunch: ["7E"],
			firepunch: ["7E"],
			icepunch: ["7E"],
			workup: ["7M"],
			toxic: ["7M"],
			bulkup: ["7M"],
			hyperbeam: ["7M"],
			protect: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			smackdown: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			earthquake: ["7M"],
			return: ["7M"],
			psychic: ["7M"],
			brickbreak: ["7M"],
			doubleteam: ["7M"],
			sandstorm: ["7M"],
			rocktomb: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			lowsweep: ["7M"],
			round: ["7M"],
			skydrop: ["7M"],
			acrobatics: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			rockpolish: ["7M"],
			stoneedge: ["7M"],
			thunderwave: ["7M"],
			fly: ["7M"],
			psychup: ["7M"],
			bulldoze: ["7M"],
			rockslide: ["7M"],
			poisonjab: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			dazzlinggleam: ["7M"],
			confide: ["7M"],
		}
	},
	chy: {
		learnset: {
			batonpass: ["7L1"],
			outrage: ["7L1"],
			dragonpulse: ["7L1"],
			guardsplit: ["7L1"],
			switcheroo: ["7L1"],
			pursuit: ["7L1"],
			quickattack: ["7L1"],
			twister: ["7L4"],
			confusion: ["7L10"],
			torment: ["7L13"],
			bodyslam: ["7L19"],
			dragonbreath: ["7L22"],
			glare: ["7L28"],
			headbutt: ["7L31"],
			partingshot: ["7L37"],
			hypnosis: ["7L40"],
			plague: ["7L43"],
			hypervoice: ["7L49"],
			dragonrush: ["7E"],
			speedswap: ["7E"],
			coil: ["7E"],
			workup: ["7M"],
			psyshock: ["7M"],
			calmmind: ["7M"],
			roar: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			flamethrower: ["7M"],
			fireblast: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			focusblast: ["7M"],
			energyball: ["7M"],
			brutalswing: ["7M"],
			payback: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			wildcharge: ["7M"],
			snarl: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	quemelo: {
		learnset: {
			batonpass: ["7L1"],
			outrage: ["7L1"],
			dragonpulse: ["7L1"],
			guardsplit: ["7L1"],
			switcheroo: ["7L1"],
			pursuit: ["7L1"],
			quickattack: ["7L1"],
			twister: ["7L4"],
			confusion: ["7L10"],
			torment: ["7L13"],
			bodyslam: ["7L19"],
			dragonbreath: ["7L22"],
			glare: ["7L28"],
			headbutt: ["7L31"],
			partingshot: ["7L37"],
			hypnosis: ["7L40"],
			plague: ["7L43"],
			hypervoice: ["7L49"],
			dragonrush: ["7E"],
			speedswap: ["7E"],
			coil: ["7E"],
			workup: ["7M"],
			psyshock: ["7M"],
			calmmind: ["7M"],
			roar: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			flamethrower: ["7M"],
			fireblast: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			focusblast: ["7M"],
			energyball: ["7M"],
			brutalswing: ["7M"],
			payback: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			wildcharge: ["7M"],
			snarl: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	glatise: {
		learnset: {
			batonpass: ["7L1"],
			outrage: ["7L1"],
			dragonpulse: ["7L1"],
			guardsplit: ["7L1"],
			switcheroo: ["7L1"],
			pursuit: ["7L1"],
			quickattack: ["7L1"],
			twister: ["7L4"],
			confusion: ["7L10"],
			torment: ["7L13"],
			bodyslam: ["7L19"],
			dragonbreath: ["7L22"],
			glare: ["7L28"],
			headbutt: ["7L31"],
			partingshot: ["7L37"],
			hypnosis: ["7L40"],
			plague: ["7L43"],
			hypervoice: ["7L49"],
			dragonrush: ["7E"],
			speedswap: ["7E"],
			coil: ["7E"],
			workup: ["7M"],
			psyshock: ["7M"],
			calmmind: ["7M"],
			roar: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			solarbeam: ["7M"],
			thunderbolt: ["7M"],
			thunder: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			psychic: ["7M"],
			shadowball: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			flamethrower: ["7M"],
			fireblast: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			echoedvoice: ["7M"],
			focusblast: ["7M"],
			energyball: ["7M"],
			brutalswing: ["7M"],
			payback: ["7M"],
			gigaimpact: ["7M"],
			thunderwave: ["7M"],
			psychup: ["7M"],
			infestation: ["7M"],
			poisonjab: ["7M"],
			grassknot: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			trickroom: ["7M"],
			wildcharge: ["7M"],
			snarl: ["7M"],
			naturepower: ["7M"],
			darkpulse: ["7M"],
			confide: ["7M"],
		}
	},
	uisge: {
		learnset: {
		}
	},
	talamh: {
		learnset: {
		}
	},
	adhair: {
		learnset: {
		}
	},
	infineer: {
		learnset: {
		}
	},
	remordial: {
		learnset: {
		}
	},
	doduoistor: {
		learnset: {
			acupressure: ["7L33"],
			aerialace: ["7M"],
			agility: ["7L26"],
			assurance: ["7E"],
			attract: ["7M"],
			bravebird: ["7E"],
			confide: ["7M"],
			doublehit: ["7L22"],
			doubleteam: ["7M"],
			drillpeck: ["7L43"],
			echoedvoice: ["7M"],
			endeavor: ["7L47", "7E"],
			facade: ["7M"],
			feintattack: ["7E"],
			flail: ["7E"],
			flashcannon: ["7M"],
			fly: ["7M"],
			frustration: ["7M"],
			furyattack: ["7L12"],
			growl: ["7L1"],
			hiddenpower: ["7M"],
			irondefense: ["7E"],
			ironhead: ["7E"],
			jumpkick: ["7L40"],
			mirrormove: ["7E"],
			naturalgift: ["7E"],
			peck: ["7L1"],
			pluck: ["7L19"],
			protect: ["7M"],
			pursuit: ["7L15"],
			quickattack: ["7L5"],
			rest: ["7M"],
			return: ["7M"],
			roost: ["7M"],
			round: ["7M"],
			sleeptalk: ["7M"],
			steelwing: ["7M", "7L9"],
			smartstrike: ["7M"],
			substitute: ["7M"],
			sunnyday: ["7M"],
			swagger: ["7M"],
			swordsdance: ["7M", "7L36"],
			thief: ["7M"],
			impalingfeather: ["7L50"],
			toxic: ["7M"],
			heavyslam: ["7L29"],
			workup: ["7M"],
		}
	},
			dodrioistor: {
				learnset: {
					acupressure: ["7L34"],
					aerialace: ["7M"],
					agility: ["7L260"],
					assurance: ["7E"],
					attract: ["7M"],
					bravebird: ["7E"],
					confide: ["7M"],
					doublehit: ["7L22"],
					doubleteam: ["7M"],
					drillpeck: ["7L47"],
					echoedvoice: ["7M"],
					endeavor: ["7L52", "7E"],
					facade: ["7M"],
					feintattack: ["7E"],
					flail: ["7E"],
					flashcannon: ["7M"],
					fly: ["7M"],
					frustration: ["7M"],
					furyattack: ["7L121"],
					gigaimpact: ["7M"],
					growl: ["7L1"],
					hiddenpower: ["7M"],
					hyperbeam: ["7M"],
					irondefense: ["7E"],
					ironhead: ["7E"],
					jumpkick: ["7L43"],
					mirrormove: ["7E"],
					naturalgift: ["7E"],
					payback: ["7M"],
					peck: ["7L1"],
					pluck: ["7L19"],
					protect: ["7M"],
					pursuit: ["7L15"],
					quickattack: ["7L5", "7E", "7L1"],
					rest: ["7M"],
					return: ["7M"],
					roost: ["7M"],
					round: ["7M"],
					sleeptalk: ["7M"],
					smartstrike: ["7M"],
					steelwing: ["7M", "7L8", "7L1"],
					substitute: ["7M"],
					sunnyday: ["7M"],
					supersonic: ["7E"],
					swagger: ["7M"],
					swordsdance: ["7M", "7L38"],
					taunt: ["7M"],
					thief: ["7M"],
					impalingfeather: ["7L56"],
					torment: ["7M"],
					toxic: ["7M"],
					triattack: ["7L1"],
					heavyslam: ["7L29"],
					workup: ["7M"],
				}
			},
			laprasistor: {
				learnset: {
					ancientpower: ["7E", "6E", "5E", "4T", "4E"],
					attract: ["7M", "6M", "5M", "4M", "3M"],
					auroraveil: ["7L27", "7M"],
					avalanche: ["7E", "6E", "5E", "4M"],
					blizzard: ["7M", "6M", "5M", "4M", "3M", "3S0"],
					bodyslam: ["7L18", "6L18", "5L18", "4L18", "3T", "3L13"],
					cleansedsoul: ["7L37"],
					bulldoze: ["7M", "6M", "5M"],
					confide: ["7M", "6M"],
					confuseray: ["7L7", "6L7", "5L7", "5D", "4L7", "3L19"],
					curse: ["7E", "6E", "5E", "4E", "3E"],
					destinybond: ["7E"],
					dimensionalrift: ["7L47"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					dragondance: ["7E", "6E", "5E", "4E", "3E"],
					dragonpulse: ["7E", "6T", "6E", "5T", "5E", "4M"],
					dreameater: ["7M", "6M", "5M", "4M", "3T"],
					echoedvoice: ["7M", "6M", "5M"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					fissure: ["7E", "6E", "5E", "4E"],
					foresight: ["7E", "6E", "5E", "4E", "3E"],
					freezedry: ["7E", "6E"],
					frostbreath: ["7M", "6M", "5M"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					futuresight: ["7E", "6E", "5E"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					growl: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					hail: ["7M", "7L22", "6M", "5M", "4M", "3M"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					horndrill: ["7E", "6E", "5E", "5D", "4E", "3E"],
					hydropump: ["7E"],
					hyperbeam: ["7M", "6M", "5M", "4M", "3M"],
					icebeam: ["7M", "7L32", "6M", "6L32", "5M", "5L32", "4M", "4L32", "3M", "3L31"],
					iceshard: ["7L10", "6L10", "5L10", "4L10"],
					luckychant: ["7L4"],
					mist: ["7L4", "6L4", "5L4", "4L4", "3L7"],
					ominouswind: ["7L14"],
					perishsong: ["7E"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psychic: ["7M", "6M", "5M", "4M", "3M"],
					raindance: ["7M", "6M", "6L22", "5M", "5L22", "4M", "4L22", "3M", "3L37", "3S0"],
					refresh: ["7E", "6E", "5E", "4E", "3E"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					roar: ["7M", "6M", "5M", "4M", "3M"],
					round: ["7M", "6M", "5M"],
					safeguard: ["7M", "7L43", "6M", "6L43", "5M", "5L43", "4M", "4L43", "3M", "3L43"],
					sheercold: ["7L50", "6L50", "5L55", "4L55", "3L55"],
					sing: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					sleeptalk: ["7M", "7E", "6M", "6E", "5T", "5E", "4M", "4E", "3T", "3E"],
					smartstrike: ["7M"],
					substitute: ["7M", "6M", "5M", "4M", "4E", "3T", "3E"],
					surf: ["7M", "6M", "5M", "4M", "3M"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					thunder: ["7M", "6M", "5M", "4M", "3M"],
					thunderbolt: ["7M", "6M", "5M", "4M", "3M"],
					tickle: ["7E", "6E", "5E", "4E", "3E"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					waterfall: ["7M", "6M", "5M", "4M", "3M"],
					watergun: ["7E"],
					whirlpool: ["7E", "6E", "5E", "4M", "4E"],
				}
			},
			rioluistor: {
				learnset: {
					agility: ["7E"],
					attract: ["7M"],
					bite: ["7E"],
					blazekick: ["7E"],
					brickbreak: ["7M"],
					bulkup: ["7M"],
					bulldoze: ["7M"],
					circlethrow: ["7E"],
					confide: ["7M"],
					copycat: ["7L19"],
					counter: ["7L6"],
					crosschop: ["7E"],
					crunch: ["7E"],
					dazzlinggleam: ["7M"],
					detect: ["7E"],
					divertissement: ["7L1"],
					doubleteam: ["7M"],
					earthquake: ["7M"],
					endure: ["7L1"],
					facade: ["7M"],
					fakeout: ["7M"],
					feint: ["7L11"],
					finalgambit: ["7L50"],
					fling: ["7M"],
					focusblast: ["7M"],
					followme: ["7E"],
					forcepalm: ["7L15"],
					foresight: ["7L1"],
					frustration: ["7M"],
					hiddenpower: ["7M"],
					highjumpkick: ["7E"],
					lowkick: ["7E"],
					lowsweep: ["7M"],
					mindreader: ["7E"],
					nastyplot: ["7L47"],
					payback: ["7M"],
					poisonjab: ["7M"],
					playrough: ["7L39"],
					protect: ["7M"],
					quickattack: ["7L1"],
					raindance: ["7M"],
					rest: ["7M"],
					return: ["7M"],
					reversal: ["7L29"],
					roar: ["7M"],
					rockslide: ["7M"],
					rocktomb: ["7M"],
					round: ["7M"],
					screech: ["7L24"],
					shadowclaw: ["7M"],
					skyuppercut: ["7E"],
					sleeptalk: ["7M"],
					sparklingstrike: ["7E", "7M"],
					substitute: ["7M"],
					sunnyday: ["7M"],
					swagger: ["7M"],
					swordsdance: ["7M"],
					toxic: ["7M"],
					vacuumwave: ["7E"],
					workup: ["7M"],
				}
			},
			lucarioistor: {
				learnset: {
					agility: ["7E"],
					attract: ["7M"],
					aurasphere: ["7L1", "7L2"],
					bite: ["7E"],
					blazekick: ["7E"],
					brickbreak: ["7M"],
					bulkup: ["7M"],
					bulldoze: ["7M"],
					calmmind: ["7M", "7L47"],
					circlethrow: ["7E"],
					closecombat: ["7L55"],
					confide: ["7M"],
					counter: ["7L6"],
					crosschop: ["7E"],
					crunch: ["7E"],
					darkpulse: ["7M"],
					dazzlinggleam: ["7M"],
					detect: ["7L1", "7E"],
					divertissement: ["7L1"],
					doubleteam: ["7M"],
					dragonpulse: ["7L60"],
					earthquake: ["7M"],
					encore: ["7L42"],
					extremespeed: ["7L65"],
					facade: ["7M"],
					fakeout: ["7E"],
					feint: ["7L11"],
					fling: ["7M"],
					focusblast: ["7M"],
					followme: ["7E"],
					foresight: ["7L1"],
					frustration: ["7M"],
					gigaimpact: ["7M"],
					healpulse: ["7L51"],
					hiddenpower: ["7M"],
					highjumpkick: ["7E"],
					hyperbeam: ["7M"],
					hypervoice: ["7L24"],
					spotlight: ["7L1"],
					lowkick: ["7E"],
					lowsweep: ["7M"],
					mefirst: ["7L37"],
					mindreader: ["7E"],
					payback: ["7M"],
					playrough: ["7L29"],
					poisonjab: ["7M"],
					poweruppunch: ["7L15"],
					protect: ["7M"],
					psychic: ["7M"],
					quickattack: ["7L1"],
					quickguard: ["7L33"],
					raindance: ["7M"],
					rest: ["7M"],
					return: ["7M"],
					roar: ["7M"],
					rockslide: ["7M"],
					rocktomb: ["7M"],
					round: ["7M"],
					shadowball: ["7M"],
					shadowclaw: ["7M"],
					skyuppercut: ["7E"],
					sleeptalk: ["7M"],
					sparklingstrike: ["7L19", "7E", "7M"],
					stoneedge: ["7M"],
					substitute: ["7M"],
					sunnyday: ["7M"],
					swagger: ["7M"],
					swordsdance: ["7M"],
					toxic: ["7M"],
					vacuumwave: ["7E"],
					workup: ["7M"],
				}
			},
			/* MOVEPOOL CHANGES */
			mrmime: {
				learnset: {
					aerialace: ["7M", "6M", "5M", "4M"],
					attract: ["7M", "6M", "5M", "4M", "3M"],
					barrier: ["7L1", "6L1", "5L1", "5D", "4L1", "3L1"],
					batonpass: ["7L46", "6L46", "5L46", "4L46", "3L47"],
					bodyslam: ["3T"],
					brickbreak: ["7M", "6M", "5M", "4M", "3M"],
					calmmind: ["7M", "6M", "5M", "4M", "3M"],
					captivate: ["4M"],
					chargebeam: ["7M", "6M", "5M", "4M"],
					confide: ["7M", "6M"],
					confuseray: ["7E", "6E", "5E", "4E"],
					confusion: ["7L1", "6L1", "5L1", "4L1", "3L5"],
					copycat: ["7L4", "6L4", "5L4", "4L4"],
					counter: ["3T"],
					covet: ["6T", "5T"],
					dazzlinggleam: ["7M", "6M"],
					divertissement: ["7L1"],
					doubleedge: ["3T"],
					doubleslap: ["7L11", "6L11", "5L15", "4L15", "3L15"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					drainpunch: ["6T", "5T", "4M"],
					dreameater: ["7M", "6M", "5M", "4M", "3T"],
					encore: ["7L18", "6L18", "5L11", "4L11", "3L25", "3S0"],
					endure: ["4M", "3T"],
					energyball: ["7M", "6M", "5M", "4M"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					fakeout: ["7E", "6E", "5E", "4E", "3E"],
					firepunch: ["6T", "5T", "4T", "3T"],
					flash: ["6M", "5M", "4M", "3M"],
					fling: ["7M", "6M", "5M", "4M"],
					focusblast: ["7M", "6M", "5M", "4M"],
					focuspunch: ["6T", "4M", "3M"],
					followme: ["3S0"],
					foulplay: ["6T", "5T"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					futuresight: ["7E", "6E", "5E", "4E", "3E"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					grassknot: ["7M", "6M", "5M", "4M"],
					guardswap: ["7L1", "6L1", "5L1", "4L1"],
					headbutt: ["4T"],
					helpinghand: ["6T", "5T", "4T"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					hyperbeam: ["7M", "6M", "5M", "4M", "3M"],
					hypnosis: ["7E", "6E", "5E", "4E", "3E"],
					icepunch: ["6T", "5T", "4T", "3T"],
					icywind: ["7E", "6T", "6E", "5T", "5E"],
					infestation: ["7M", "6M"],
					irondefense: ["6T", "5T", "4T"],
					lightscreen: ["7M", "7L22", "6M", "6L22", "5M", "5L22", "4M", "4L22", "3M", "3L19"],
					magicalleaf: ["7L1", "6L1", "5L1", "4L1", "3L22"],
					magiccoat: ["6T", "5T", "4T"],
					magicroom: ["7E", "6T", "6E", "5T", "5E"],
					meditate: ["7L8", "6L8", "5L8", "4L8", "3L12"],
					megakick: ["3T"],
					megapunch: ["3T"],
					metronome: ["3T"],
					mimic: ["7L15", "7E", "6L15", "6E", "5L18", "5E", "4L18", "4E", "3T", "3E"],
					mistyterrain: ["7L1", "6L1"],
					mudslap: ["4T", "3T"],
					nastyplot: ["7E", "6E", "5E", "4E"],
					naturalgift: ["4M"],
					nightmare: ["3T"],
					payback: ["7M", "6M", "5M", "4M"],
					powersplit: ["7E", "6E", "5E"],
					powerswap: ["7L1", "6L1", "5L1", "4L1"],
					poweruppunch: ["6M"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psybeam: ["7L25", "6L25", "5L25", "4L25", "3L29"],
					psychic: ["7M", "7L39", "6M", "6L39", "5M", "5L39", "4M", "4L39", "3M", "3L43", "3S0"],
					psychup: ["7M", "6M", "5M", "4M", "4E", "3T", "3E"],
					psyshock: ["7M", "6M", "5M"],
					psywave: ["7L15", "6L15", "5L15"],
					quickguard: ["7L1", "6L1", "5L1"],
					raindance: ["7M", "6M", "5M", "4M", "3M"],
					recycle: ["7L32", "6T", "6L32", "5T", "5L32", "4M", "4L32", "3L33"],
					reflect: ["7M", "7L22", "6M", "6L22", "5M", "5L22", "4M", "4L22", "3M", "3L19"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					roleplay: ["7L43", "6T", "6L43", "5T", "5L43", "4T", "4L43", "3L40"],
					round: ["7M", "6M", "5M"],
					safeguard: ["7M", "7L50", "6M", "6L50", "5M", "5L50", "4M", "4L50", "3M", "3L50"],
					secretpower: ["6M", "4M", "3M"],
					seismictoss: ["3T"],
					shadowball: ["7M", "6M", "5M", "4M", "3M"],
					shockwave: ["6T", "4M", "3M"],
					signalbeam: ["6T", "5T", "4T"],
					skillswap: ["6T", "5T", "5D", "4M", "3M"],
					sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
					snatch: ["6T", "5T", "4M", "3M"],
					snore: ["6T", "5T", "4T", "3T"],
					solarbeam: ["7M", "6M", "5M", "4M", "3M"],
					substitute: ["7M", "7L29", "6M", "6L29", "5M", "5L29", "4M", "4L29", "3T", "3L8"],
					sunnyday: ["7M", "6M", "5M", "4M", "3M"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					taunt: ["7M", "6M", "5M", "4M", "3M"],
					teeterdance: ["7E", "6E", "5E", "5D", "4E"],
					telekinesis: ["5M"],
					thief: ["7M", "6M", "5M", "4M", "3M"],
					thunder: ["7M", "6M", "5M", "4M", "3M"],
					thunderbolt: ["7M", "6M", "5M", "4M", "3M"],
					thunderpunch: ["6T", "5T", "4T", "3T", "3S0"],
					thunderwave: ["7M", "6M", "5M", "4M", "3T"],
					torment: ["7M", "6M", "5M", "4M", "3M"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					trick: ["7L36", "7E", "6T", "6L36", "6E", "5T", "5L36", "5E", "4T", "4L36", "4E", "3L36", "3E"],
					trickroom: ["7M", "6M", "5M", "4M"],
					wakeupslap: ["7E", "6E", "5E", "4E"],
					wideguard: ["7L1", "6L1", "5L1"],
					wonderroom: ["6T", "5T"],
					zenheadbutt: ["6T", "5T", "4T"],
				}
			},
			jynx: {
				learnset: {
					attract: ["7M", "6M", "5M", "4M", "3M"],
					auroraveil: ["7M"],
					avalanche: ["7L39", "6L39", "5L39", "4M", "4L33"],
					blizzard: ["7M", "7L60", "6M", "6L60", "5M", "5L60", "4M", "4L55", "3M", "3L67"],
					bodyslam: ["7L44", "6L44", "5L44", "4L39", "3T", "3L51"],
					brickbreak: ["7M", "6M", "5M", "4M", "3M"],
					calmmind: ["7M", "6M", "5M", "4M", "3M"],
					captivate: ["7E", "4M"],
					confide: ["7M", "6M"],
					counter: ["3T"],
					covet: ["6T", "5T"],
					divertissement: ["7L1"],
					doubleedge: ["3T"],
					doubleslap: ["7L15", "6L15", "5L15", "4L15", "3L21"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					drainingkiss: ["7L1", "6L1"],
					drainpunch: ["6T", "5T", "4M"],
					dreameater: ["7M", "6M", "5M", "4M", "3T"],
					dynamicpunch: ["3T"],
					echoedvoice: ["7M", "6M", "5M"],
					endure: ["4M", "3T"],
					energyball: ["7M", "6M", "5M", "4M"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					fakeout: ["7E"],
					faketears: ["7L28", "6L28", "5L28", "4L25", "3L41"],
					flash: ["6M", "5M", "4M", "3M"],
					fling: ["7M", "6M", "5M", "4M"],
					focusblast: ["7M", "6M", "5M", "4M"],
					focuspunch: ["6T", "4M", "3M"],
					frostbreath: ["7M", "6M", "5M"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					grassknot: ["7M", "6M", "5M", "4M"],
					hail: ["7M", "6M", "5M", "4M", "3M"],
					headbutt: ["4T"],
					healbell: ["6T", "5T", "4T"],
					heartstamp: ["7L21", "6L21", "5L21"],
					helpinghand: ["6T", "5T", "4T"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					hyperbeam: ["7M", "6M", "5M", "4M", "3M"],
					hypervoice: ["6T", "5T"],
					icebeam: ["7M", "6M", "5M", "4M", "3M"],
					icepunch: ["7L18", "7E", "6T", "6L18", "5T", "5L18", "4T", "4L18", "3T", "3L25"],
					icywind: ["6T", "5T", "4T", "3T"],
					lick: ["7L5", "7L1", "6L1", "5L1", "4L1", "3L1"],
					lightscreen: ["7M", "6M", "5M", "4M", "3M"],
					lovelykiss: ["7L8", "7L1", "6L1", "5L1", "4L1", "3L1"],
					magiccoat: ["6T", "5T", "4T"],
					magicroom: ["6T", "5T"],
					meanlook: ["7L25", "6L25", "5L25", "4L21", "3L35"],
					meditate: ["7E"],
					megakick: ["3T"],
					megapunch: ["3T"],
					metronome: ["3T"],
					mimic: ["3T"],
					miracleeye: ["7E"],
					mudslap: ["4T", "3T"],
					nastyplot: ["7E"],
					naturalgift: ["4M"],
					nightmare: ["3T"],
					payback: ["7M", "6M", "5M", "4M"],
					perishsong: ["7L55", "7L1", "6L1", "5L55", "4L49", "3L57"],
					pound: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					powdersnow: ["7L11", "7L1", "6L1", "5L1", "4L1", "3L1"],
					poweruppunch: ["6M"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psychic: ["7M", "6M", "5M", "4M", "3M"],
					psychup: ["7M", "6M", "5M", "4M", "3T"],
					psyshock: ["7M", "6M", "5M"],
					raindance: ["7M", "6M", "5M", "4M", "3M"],
					recycle: ["6T", "5T", "4M"],
					reflect: ["7M", "6M", "5M", "4M", "3M"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					roleplay: ["6T", "5T", "4T"],
					round: ["7M", "6M", "5M"],
					secretpower: ["6M", "4M", "3M"],
					seismictoss: ["3T"],
					shadowball: ["7M", "6M", "5M", "4M", "3M"],
					signalbeam: ["6T", "5T", "4T"],
					skillswap: ["6T", "5T", "4M", "3M"],
					sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
					snore: ["6T", "5T", "4T", "3T"],
					substitute: ["7M", "6M", "5M", "4M", "3T"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					taunt: ["7M", "6M", "5M", "4M", "3M"],
					telekinesis: ["5M"],
					thief: ["7M", "6M", "5M", "4M", "3M"],
					torment: ["7M", "6M", "5M", "4M", "3M"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					wakeupslap: ["7L33", "7E", "6L33", "5L33", "4L28"],
					waterpulse: ["6T", "4M", "3M"],
					wish: ["7E"],
					wringout: ["7L49", "6L49", "5L49", "4L44"],
					zenheadbutt: ["6T", "5T", "4T"],
				}
			},
			bronzor: {
				learnset: {
					ancientpower: ["4T"],
					bulldoze: ["7M", "6M", "5M"],
					calmmind: ["7M", "6M", "5M", "4M"],
					chargebeam: ["7M", "6M", "5M", "4M"],
					confide: ["7M", "6M"],
					confuseray: ["7L11", "6L11", "5L14", "4L14"],
					confusion: ["7L1", "6L1", "5L1", "4L1"],
					dimensionalrift: ["7L53"],
					doubleteam: ["7M", "6M", "5M", "4M"],
					dreameater: ["7M", "6M", "5M", "4M"],
					earthquake: ["7M", "6M", "5M", "4M"],
					endure: ["4M"],
					extrasensory: ["7L39", "6L39", "5L19", "4L19"],
					facade: ["7M", "6M", "5M", "4M"],
					feintattack: ["7L21", "6L21", "5L41", "4L41"],
					flash: ["6M", "5M", "4M"],
					flashcannon: ["7M", "6M", "5M", "4M"],
					frustration: ["7M", "6M", "5M", "4M"],
					futuresight: ["7L29", "6L29", "5L37", "4L37"],
					grassknot: ["7M", "6M", "5M", "4M"],
					gravity: ["6T", "5T", "5D", "4T"],
					gyroball: ["7M", "7L35", "6M", "6L35", "5M", "5L35", "4M", "4L35"],
					healblock: ["7L45", "6L45", "5L52", "4L52"],
					heavyslam: ["7L49", "6L49", "5L54"],
					hiddenpower: ["7M", "6M", "5M", "4M"],
					hypnosis: ["7L5", "6L5", "5L7", "5D", "4L7"],
					imprison: ["7L9", "6L9", "5L12", "4L12"],
					irondefense: ["7L19", "6T", "6L19", "5T", "5L26", "4L26"],
					lightscreen: ["7M", "6M", "5M", "4M"],
					metalsound: ["7L31", "6L31", "5L31"],
					naturalgift: ["4M"],
					payback: ["7M", "7L41", "6M", "6L41", "5M", "5L49", "4M", "4L49"],
					protect: ["7M", "6M", "5M", "4M"],
					psychic: ["7M", "6M", "5M", "4M"],
					psychup: ["7M", "6M", "5M", "4M"],
					psyshock: ["7M", "6M", "5M"],
					psywave: ["7L15", "6L15", "5L15"],
					raindance: ["7M", "6M", "5M", "4M"],
					recycle: ["6T", "5T", "4M"],
					reflect: ["7M", "6M", "5M", "4M"],
					rest: ["7M", "6M", "5M", "4M"],
					return: ["7M", "6M", "5M", "4M"],
					rockpolish: ["7M", "6M", "5M", "4M"],
					rockslide: ["7M", "6M", "5M", "4M"],
					rocktomb: ["7M", "6M", "5M", "4M"],
					rollout: ["4T"],
					round: ["7M", "6M", "5M"],
					safeguard: ["7M", "7L25", "6M", "6L25", "5M", "5L30", "4M", "4L30"],
					sandstorm: ["7M", "6M", "5M", "4M"],
					secretpower: ["6M", "4M"],
					shadowball: ["7M", "6M", "5M", "4M"],
					signalbeam: ["6T", "5T", "4T"],
					skillswap: ["6T", "5T", "5D", "4M"],
					sleeptalk: ["7M", "6M", "5T", "4M"],
					snore: ["6T", "5T", "4T"],
					solarbeam: ["7M", "6M", "5M", "4M"],
					stealthrock: ["6T", "5T", "4M"],
					substitute: ["7M", "6M", "5M", "4M"],
					sunnyday: ["7M", "6M", "5M", "4M"],
					swagger: ["7M", "6M", "5M", "4M"],
					tackle: ["7L1", "6L1", "5L1", "4L1"],
					telekinesis: ["5M"],
					toxic: ["7M", "6M", "5M", "4M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					wonderroom: ["6T", "5T"],
				}
			},
			bronzong: {
				learnset: {
					ancientpower: ["4T"],
					block: ["7L1", "6T", "6L33", "5T", "5L33", "4T", "4L33"],
					bulldoze: ["7M", "6M", "5M"],
					calmmind: ["7M", "6M", "5M", "4M"],
					chargebeam: ["7M", "6M", "5M", "4M"],
					confide: ["7M", "6M"],
					confuseray: ["7L11", "6L11", "5L14", "4L14"],
					confusion: ["7L1", "6L1", "5L1", "4L1"],
					dimensionalrift: ["7L64"],
					doubleteam: ["7M", "6M", "5M", "4M"],
					dreameater: ["7M", "6M", "5M", "4M"],
					earthquake: ["7M", "6M", "5M", "4M"],
					endure: ["4M"],
					explosion: ["7M", "6M", "5M", "4M"],
					extrasensory: ["7L42", "6L42", "5L19", "4L19"],
					facade: ["7M", "6M", "5M", "4M"],
					feintattack: ["7L21", "6L21", "5L50", "4L50"],
					flash: ["6M", "5M", "4M"],
					flashcannon: ["7M", "6M", "5M", "4M"],
					frustration: ["7M", "6M", "5M", "4M"],
					futuresight: ["7L29", "6L29", "5L43", "4L43"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					grassknot: ["7M", "6M", "5M", "4M"],
					gravity: ["6T", "5T", "4T"],
					gyroball: ["7M", "7L36", "6M", "6L36", "5M", "5L38", "4M", "4L38"],
					healblock: ["7L52", "6L52", "5L67", "4L67"],
					heavyslam: ["7L58", "6L58", "5L72"],
					hiddenpower: ["7M", "6M", "5M", "4M"],
					hyperbeam: ["7M", "6M", "5M", "4M"],
					hypnosis: ["7L5", "7L1", "6L1", "5L1", "4L1"],
					imprison: ["7L9", "7L1", "6L1", "5L1", "4L1"],
					irondefense: ["7L19", "6T", "6L19", "5T", "5L26", "4L26"],
					ironhead: ["6T", "5T", "4T"],
					lightscreen: ["7M", "6M", "5M", "4M"],
					metalsound: ["7L31", "6L31", "5L31"],
					naturalgift: ["4M"],
					payback: ["7M", "7L46", "6M", "6L46", "5M", "5L61", "4M", "4L61"],
					protect: ["7M", "6M", "5M", "4M"],
					psychic: ["7M", "6M", "5M", "4M"],
					psychup: ["7M", "6M", "5M", "4M"],
					psyshock: ["7M", "6M", "5M"],
					psywave: ["7L15", "6L15", "5L15"],
					raindance: ["7M", "7L1", "6M", "6L1", "5M", "5L1", "4M", "4L1"],
					recycle: ["6T", "5T", "4M"],
					reflect: ["7M", "6M", "5M", "4M"],
					rest: ["7M", "6M", "5M", "4M"],
					return: ["7M", "6M", "5M", "4M"],
					rockpolish: ["7M", "6M", "5M", "4M"],
					rockslide: ["7M", "6M", "5M", "4M"],
					rocksmash: ["6M", "5M", "4M"],
					rocktomb: ["7M", "6M", "5M", "4M"],
					rollout: ["4T"],
					round: ["7M", "6M", "5M"],
					safeguard: ["7M", "7L25", "6M", "6L25", "5M", "5L30", "4M", "4L30"],
					sandstorm: ["7M", "6M", "5M", "4M"],
					secretpower: ["6M", "4M"],
					shadowball: ["7M", "6M", "5M", "4M"],
					signalbeam: ["6T", "5T", "4T"],
					skillswap: ["6T", "5T", "4M"],
					sleeptalk: ["7M", "6M", "5T", "4M"],
					snore: ["6T", "5T", "4T"],
					solarbeam: ["7M", "6M", "5M", "4M"],
					stealthrock: ["6T", "5T", "4M"],
					strength: ["6M", "5M", "4M"],
					substitute: ["7M", "6M", "5M", "4M"],
					sunnyday: ["7M", "7L1", "6M", "6L1", "5M", "5L1", "4M", "4L1"],
					swagger: ["7M", "6M", "5M", "4M"],
					tackle: ["7L1", "6L1", "5L1", "4L1"],
					telekinesis: ["5M"],
					toxic: ["7M", "6M", "5M", "4M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					wonderroom: ["6T", "5T"],
					zenheadbutt: ["6T", "5T", "4T"],
				}
			},
			hoopa: {
				learnset: {
					allyswitch: ["7L1", "6L1"],
					astonish: ["7L6", "6L6", "6S0"],
					block: ["6T"],
					brickbreak: ["7M", "6M"],
					calmmind: ["7M", "6M"],
					chargebeam: ["7M", "6M"],
					confide: ["7M", "6M"],
					confusion: ["7L1", "6L1"],
					covet: ["6T"],
					darkpulse: ["7M", "6L55"],
					destinybond: ["7L1", "6L1"],
					dimensionalrift: ["7L100"],
					doubleteam: ["7M", "6M"],
					drainpunch: ["6T"],
					dreameater: ["7M", "6M"],
					dualchop: ["6T"],
					embargo: ["7M", "6M"],
					energyball: ["7M", "6M"],
					facade: ["7M", "6M"],
					firepunch: ["6T"],
					flash: ["6M"],
					fling: ["7M", "6M"],
					focusblast: ["7M", "6M"],
					focuspunch: ["6T"],
					foulplay: ["6T"],
					frustration: ["7M", "6M"],
					gigaimpact: ["7M", "6M"],
					grassknot: ["7M", "6M"],
					gravity: ["6T"],
					guardsplit: ["7L29", "6L29"],
					gunkshot: ["6T"],
					hiddenpower: ["7M", "6M"],
					hyperbeam: ["7M", "6M"],
					hyperspacefury: ["6L1"],
					hyperspacehole: ["7L85", "7L1", "6L1", "6S0"],
					icepunch: ["6T"],
					knockoff: ["6T", "6L46"],
					lastresort: ["6T"],
					lightscreen: ["7M", "7L15", "6M", "6L15"],
					magiccoat: ["7L10", "6T", "6L10"],
					magicroom: ["6T"],
					nastyplot: ["7L68", "6L68", "6S0"],
					phantomforce: ["7L35", "6L35"],
					powersplit: ["7L29", "6L29"],
					poweruppunch: ["6M"],
					protect: ["7M", "6M"],
					psybeam: ["7L19", "6L15"],
					psychic: ["7M", "7L75", "6M", "6L75", "6S0"],
					psychup: ["7M", "6M"],
					psyshock: ["7M", "6M"],
					quash: ["7M", "6M"],
					raindance: ["7M", "6M"],
					recycle: ["6T"],
					reflect: ["7M", "6M"],
					rest: ["7M", "6M"],
					return: ["7M", "6M"],
					roleplay: ["6T"],
					round: ["7M", "6M"],
					safeguard: ["7M", "6M"],
					secretpower: ["6M"],
					shadowball: ["7M", "7L55", "6M", "6L55"],
					shockwave: ["6T"],
					signalbeam: ["6T"],
					skillswap: ["7L25", "6T", "6L25"],
					sleeptalk: ["7M", "6M"],
					snatch: ["6T"],
					snore: ["6T"],
					substitute: ["7M", "6M"],
					sunnyday: ["7M", "6M"],
					swagger: ["7M", "6M"],
					taunt: ["7M", "6M"],
					thief: ["7M", "6M"],
					thunderbolt: ["7M", "6M"],
					thunderpunch: ["6T"],
					thunderwave: ["7M", "6M"],
					torment: ["7M", "6M"],
					toxic: ["7M", "6M"],
					trick: ["7L1", "6T", "6L1"],
					trickroom: ["7M", "7L50", "6M", "6L50"],
					uproar: ["6T"],
					wonderroom: ["7L50", "6T", "6L50"],
					zenheadbutt: ["7L46", "6T", "6L46"],
				}
			},
			gastly: {
				learnset: {
					astonish: ["7E", "6E", "5E", "4E", "3E"],
					attract: ["7M", "6M", "5M", "4M", "3M"],
					captivate: ["4M"],
					clearsmog: ["7E", "6E", "5E"],
					confide: ["7M", "6M"],
					confuseray: ["7L19", "6L19", "5L19", "4L19", "3L21"],
					curse: ["7L12", "6L12", "5L12", "4L12", "3L13"],
					darkpulse: ["7M", "7L36", "6M", "6L36", "5T", "5L36", "4M", "4L36"],
					dazzlinggleam: ["7M", "6M"],
					destinybond: ["7L40", "6L40", "5L40", "4L40", "3L33"],
					dimensionalrift: ["7L51"],
					disable: ["7E", "6E", "5E", "5D", "4E"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					dreameater: ["7M", "7L33", "6M", "6L33", "5M", "5L33", "4M", "4L33", "3T", "3L28"],
					embargo: ["7M", "6M", "5M", "4M"],
					endure: ["4M", "3T"],
					energyball: ["7M", "6M", "5M", "4M"],
					explosion: ["7M", "6M", "5M", "4M", "4E", "3T", "3E"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					firepunch: ["7E", "6T", "6E", "5T", "5E", "4T", "4E"],
					foulplay: ["6T", "5T"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					gigadrain: ["6T", "5T", "4M", "3M"],
					grudge: ["7E", "6E", "5E", "4E", "3E"],
					haze: ["7E", "6E", "5E", "4E", "3E"],
					hex: ["7L43", "6L43", "5L43"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					hypnosis: ["7L1", "6L1", "5L1", "5D", "4L1", "3L1"],
					icepunch: ["7E", "6T", "6E", "5T", "5E", "4T", "4E"],
					icywind: ["6T", "5T", "4T"],
					infestation: ["7M", "6M"],
					knockoff: ["6T", "5T", "4T"],
					lick: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					meanlook: ["7L8", "6L8", "5L8", "4L8", "3L13"],
					mimic: ["3T"],
					naturalgift: ["4M"],
					nightmare: ["7L47", "6L47", "5L47", "4L43", "3T", "3L41"],
					nightshade: ["7L15", "6L15", "5L15", "4L15", "3L16"],
					ominouswind: ["4T"],
					painsplit: ["6T", "5T", "4T"],
					payback: ["7M", "7L26", "6M", "6L26", "5M", "5L26", "4M", "4L26"],
					perishsong: ["7E", "6E", "5E", "4E", "3E"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psychic: ["7M", "6M", "5M", "4M", "3M"],
					psychup: ["7M", "6M", "5M", "4M", "3T"],
					psywave: ["7E", "6E", "5E", "4E", "3E"],
					raindance: ["7M", "6M", "5M", "4M", "3M"],
					reflecttype: ["7E", "6E"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					round: ["7M", "6M", "5M"],
					scaryface: ["7E", "6E", "5E"],
					secretpower: ["6M", "4M", "3M"],
					selfdestruct: ["3T"],
					shadowball: ["7M", "7L29", "6M", "6L29", "5M", "5L29", "4M", "4L29", "3M", "3L36"],
					skillswap: ["6T", "5T", "4M", "3M"],
					sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
					sludgebomb: ["7M", "6M", "5M", "4M", "3M"],
					sludgewave: ["5D"],
					smog: ["7E", "6E", "5E"],
					snatch: ["6T", "5T", "4M", "3M"],
					snore: ["6T", "5T", "4T", "3T"],
					spite: ["7L5", "6T", "6L5", "5T", "5L5", "4T", "4L5", "3L8"],
					substitute: ["7M", "6M", "5M", "4M", "3T"],
					suckerpunch: ["7L22", "6L22", "5L22", "4T", "4L22"],
					sunnyday: ["7M", "6M", "5M", "4M", "3M"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					taunt: ["7M", "6M", "5M", "4M", "3M"],
					telekinesis: ["5M"],
					thief: ["7M", "6M", "5M", "4M", "3M"],
					thunderbolt: ["7M", "6M", "5M", "4M", "3M"],
					thunderpunch: ["7E", "6T", "6E", "5T", "5E", "4T", "4E"],
					torment: ["7M", "6M", "5M", "4M", "3M"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					uproar: ["6T", "5T", "4T"],
					venoshock: ["7M", "6M", "5M"],
					willowisp: ["7M", "6M", "5M", "4M", "4E", "3E"],
					wonderroom: ["6T", "5T"],
				}
			},
			haunter: {
				learnset: {
					attract: ["7M", "6M", "5M", "4M", "3M"],
					captivate: ["4M"],
					confide: ["7M", "6M"],
					confuseray: ["7L19", "6L19", "5L19", "5S0", "4L19", "3L21"],
					curse: ["7L12", "6L12", "5L12", "4L12", "3L13"],
					darkpulse: ["7M", "7L44", "6M", "6L44", "5T", "5L44", "4M", "4L44"],
					dazzlinggleam: ["7M", "6M"],
					destinybond: ["7L50", "6L50", "5L50", "4L50", "3L39"],
					dimensionalrift: ["7L67"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					dreameater: ["7M", "7L39", "6M", "6L39", "5M", "5L39", "4M", "4L39", "3T", "3L31"],
					embargo: ["7M", "6M", "5M", "4M"],
					endure: ["4M", "3T"],
					energyball: ["7M", "6M", "5M", "4M"],
					explosion: ["7M", "6M", "5M", "4M", "3T"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					firepunch: ["6T", "5T", "4T"],
					fling: ["7M", "6M", "5M", "4M"],
					foulplay: ["6T", "5T"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					gigadrain: ["6T", "5T", "4M", "3M"],
					hex: ["7L55", "6L55", "5L55"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					hypnosis: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					icepunch: ["6T", "5T", "4T"],
					icywind: ["6T", "5T", "4T"],
					infestation: ["7M", "6M"],
					knockoff: ["6T", "5T", "4T"],
					lick: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					meanlook: ["7L8", "6L8", "5L8", "4L8", "3L13"],
					mimic: ["3T"],
					naturalgift: ["4M"],
					nightmare: ["7L61", "6L61", "5L61", "4L55", "3T", "3L53"],
					nightshade: ["7L15", "6L15", "5L15", "4L15", "3L16"],
					ominouswind: ["4T"],
					painsplit: ["6T", "5T", "4T"],
					payback: ["7M", "7L28", "6M", "6L28", "5M", "5L28", "5S0", "4M", "4L28"],
					poisonjab: ["7M", "6M", "5M", "4M"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psychic: ["7M", "6M", "5M", "4M", "3M"],
					psychup: ["7M", "6M", "5M", "4M", "3T"],
					raindance: ["7M", "6M", "5M", "4M", "3M"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					round: ["7M", "6M", "5M"],
					secretpower: ["6M", "4M", "3M"],
					selfdestruct: ["3T"],
					shadowball: ["7M", "7L33", "6M", "6L33", "5M", "5L33", "4M", "4L33", "3M", "3L45"],
					shadowclaw: ["7M", "6M", "5M", "4M"],
					shadowpunch: ["7L1", "6L25", "5L25", "5S0", "4L25", "3L25"],
					skillswap: ["6T", "5T", "4M", "3M"],
					sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
					sludgebomb: ["7M", "6M", "5M", "4M", "3M"],
					snatch: ["6T", "5T", "4M", "3M"],
					snore: ["6T", "5T", "4T", "3T"],
					spite: ["7L5", "7L1", "6T", "6L1", "5T", "5L1", "4T", "4L1", "3L1"],
					substitute: ["7M", "6M", "5M", "4M", "3T"],
					suckerpunch: ["7L22", "6L22", "5L22", "5S0", "4T", "4L22"],
					sunnyday: ["7M", "6M", "5M", "4M", "3M"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					taunt: ["7M", "6M", "5M", "4M", "3M"],
					telekinesis: ["5M"],
					thief: ["7M", "6M", "5M", "4M", "3M"],
					thunderbolt: ["7M", "6M", "5M", "4M", "3M"],
					thunderpunch: ["6T", "5T", "4T"],
					torment: ["7M", "6M", "5M", "4M", "3M"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					uproar: ["6T", "5T", "4T"],
					venoshock: ["7M", "6M", "5M"],
					willowisp: ["7M", "6M", "5M", "4M"],
					wonderroom: ["6T", "5T"],
				}
			},
			gengar: {
				learnset: {
					astonish: ["6S4"],
					attract: ["7M", "6M", "5M", "4M", "3M"],
					bodyslam: ["3T"],
					brickbreak: ["7M", "6M", "5M", "4M", "3M"],
					captivate: ["4M"],
					confide: ["7M", "6M"],
					confuseray: ["7L19", "6L19", "6S1", "6S2", "6S4", "5L19", "4L19", "3L21", "3S0"],
					counter: ["3T"],
					curse: ["7L12", "6L12", "5L12", "4L12", "3L13", "3S0"],
					darkpulse: ["7M", "7L44", "6M", "6L44", "5T", "5L44", "4M", "4L44"],
					dazzlinggleam: ["7M", "6M"],
					destinybond: ["7L50", "6L50", "6S3", "5L50", "4L50", "3L39"],
					dimensionalrift: ["7L67"],
					doubleedge: ["3T"],
					doubleteam: ["7M", "6M", "5M", "4M", "3M"],
					drainpunch: ["6T", "5T", "4M"],
					dreameater: ["7M", "7L39", "6M", "6L39", "5M", "5L39", "4M", "4L39", "3T", "3L31"],
					dynamicpunch: ["3T"],
					embargo: ["7M", "6M", "5M", "4M"],
					endure: ["4M", "3T"],
					energyball: ["7M", "6M", "5M", "4M"],
					explosion: ["7M", "6M", "5M", "4M", "3T"],
					facade: ["7M", "6M", "5M", "4M", "3M"],
					firepunch: ["6T", "5T", "4T", "3T"],
					fling: ["7M", "6M", "5M", "4M"],
					focusblast: ["7M", "6M", "5M", "4M"],
					focuspunch: ["6T", "4M", "3M"],
					foulplay: ["6T", "5T"],
					frustration: ["7M", "6M", "5M", "4M", "3M"],
					gigadrain: ["6T", "5T", "4M", "3M"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					headbutt: ["4T"],
					hex: ["7L55", "6L55", "5L55"],
					hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
					hyperbeam: ["7M", "6M", "6S5", "6S6", "5M", "4M", "3M"],
					hypnosis: ["7L1", "6L1", "6S5", "6S6", "5L1", "4L1", "3L1"],
					icepunch: ["6T", "5T", "4T", "3T"],
					icywind: ["6T", "5T", "4T"],
					infestation: ["7M", "6M"],
					knockoff: ["6T", "5T", "4T"],
					lick: ["7L1", "6L1", "5L1", "4L1", "3L1"],
					meanlook: ["7L8", "6L8", "6S5", "6S6", "5L8", "4L8", "3L13"],
					megakick: ["3T"],
					megapunch: ["3T"],
					metronome: ["3T"],
					mimic: ["3T"],
					naturalgift: ["4M"],
					nightmare: ["7L61", "6L61", "5L61", "4L55", "3T", "3L53"],
					nightshade: ["7L15", "6L15", "6S2", "5L15", "4L15", "3L16", "3S0"],
					ominouswind: ["4T"],
					painsplit: ["6T", "5T", "4T"],
					payback: ["7M", "7L28", "6M", "6L28", "5M", "5L28", "4M", "4L28"],
					poisonjab: ["7M", "6M", "5M", "4M"],
					poweruppunch: ["6M"],
					protect: ["7M", "6M", "5M", "4M", "3M"],
					psychic: ["7M", "6M", "6S1", "6S5", "6S6", "5M", "4M", "3M"],
					psychup: ["7M", "6M", "5M", "4M", "3T"],
					raindance: ["7M", "6M", "5M", "4M", "3M"],
					rest: ["7M", "6M", "5M", "4M", "3M"],
					return: ["7M", "6M", "5M", "4M", "3M"],
					rocksmash: ["6M", "5M", "4M", "3M"],
					roleplay: ["6T", "5T", "4T"],
					round: ["7M", "6M", "5M"],
					secretpower: ["6M", "4M", "3M"],
					seismictoss: ["3T"],
					selfdestruct: ["3T"],
					shadowball: ["7M", "7L33", "6M", "6L33", "6S3", "6S4", "5M", "5L33", "4M", "4L33", "3M", "3L45"],
					shadowclaw: ["7M", "6M", "5M", "4M"],
					shadowpunch: ["7L1", "6L25", "6S1", "6S2", "5L25", "4L25", "3L25"],
					skillswap: ["6T", "5T", "4M", "3M"],
					sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
					sludgebomb: ["7M", "6M", "6S3", "5M", "4M", "3M"],
					sludgewave: ["6S4"],
					snatch: ["6T", "5T", "4M", "3M"],
					snore: ["6T", "5T", "4T", "3T"],
					spite: ["7L5", "7L1", "6T", "6L1", "5T", "5L1", "4T", "4L1", "3L1", "3S0"],
					strength: ["6M", "5M", "4M", "3M"],
					substitute: ["7M", "6M", "5M", "4M", "3T"],
					suckerpunch: ["7L22", "6L22", "6S1", "6S2", "5L22", "4T", "4L22"],
					sunnyday: ["7M", "6M", "5M", "4M", "3M"],
					swagger: ["7M", "6M", "5M", "4M", "3T"],
					taunt: ["7M", "6M", "5M", "4M", "3M"],
					telekinesis: ["5M"],
					thief: ["7M", "6M", "5M", "4M", "3M"],
					thunder: ["7M", "6M", "5M", "4M", "3M"],
					thunderbolt: ["7M", "6M", "5M", "4M", "3M"],
					thunderpunch: ["6T", "5T", "4T", "3T"],
					torment: ["7M", "6M", "5M", "4M", "3M"],
					toxic: ["7M", "6M", "5M", "4M", "3M"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "6M", "5M", "4M"],
					uproar: ["6T", "5T", "4T"],
					venoshock: ["7M", "6M", "5M"],
					willowisp: ["7M", "6M", "6S3", "5M", "4M"],
					wonderroom: ["6T", "5T"],
				}
			},
			porygonz: {
				learnset: {
					aerialace: ["7M", "6M", "5M", "4M"],
					agility: ["7L12", "6L12", "5L12", "4L12"],
					blizzard: ["7M", "6M", "5M", "4M"],
					chargebeam: ["7M", "6M", "5M", "4M"],
					confide: ["7M", "6M"],
					conversion: ["7L1", "6L1", "5L1", "4L1"],
					conversion2: ["7L1", "6L1", "5L1", "4L1"],
					darkpulse: ["7M", "6M", "5T", "4M"],
					dimensionalrift: ["7L67"],
					discharge: ["7L40", "6L40", "5L40", "4L40"],
					doubleteam: ["7M", "6M", "5M", "4M"],
					dreameater: ["7M", "6M", "5M", "4M"],
					electroweb: ["6T", "5T"],
					embargo: ["7M", "7L34", "6M", "6L34", "5M", "5L34", "4M", "4L34"],
					endure: ["4M"],
					facade: ["7M", "6M", "5M", "4M"],
					flash: ["6M", "5M", "4M"],
					foulplay: ["6T", "5T"],
					frustration: ["7M", "6M", "5M", "4M"],
					gigaimpact: ["7M", "6M", "5M", "4M"],
					gravity: ["6T", "5T", "4T"],
					hiddenpower: ["7M", "6M", "5M", "4M"],
					hyperbeam: ["7M", "7L67", "6M", "6L67", "5M", "5L67", "4M", "4L67"],
					icebeam: ["7M", "6M", "5M", "4M"],
					icywind: ["6T", "5T", "4T"],
					irontail: ["6T", "5T", "4M"],
					lastresort: ["6T", "5T", "4T"],
					lockon: ["7L45", "6L45", "5L45", "4L45"],
					magiccoat: ["7L56", "7L1", "6T", "6L1", "5T", "5L56", "4T", "4L56"],
					magnetrise: ["7L23", "6T", "6L23", "5T", "5L23", "4L23"],
					nastyplot: ["7L1", "6L1", "5L1", "4L1"],
					naturalgift: ["4M"],
					painsplit: ["6T", "5T", "4T"],
					protect: ["7M", "6M", "5M", "4M"],
					psybeam: ["7L7", "6L7", "5L7", "4L7"],
					psychic: ["7M", "6M", "5M", "4M"],
					psychup: ["7M", "6M", "5M", "4M"],
					psyshock: ["7M", "6M", "5M"],
					raindance: ["7M", "6M", "5M", "4M"],
					recover: ["7L18", "6L18", "5L18", "4L18"],
					recycle: ["6T", "5T", "4M"],
					rest: ["7M", "6M", "5M", "4M"],
					return: ["7M", "6M", "5M", "4M"],
					round: ["7M", "6M", "5M"],
					secretpower: ["6M", "4M"],
					shadowball: ["7M", "6M", "5M", "4M"],
					shockwave: ["6T", "4M"],
					signalbeam: ["7L29", "6T", "6L29", "5T", "5L29", "4T", "4L29"],
					sleeptalk: ["7M", "6M", "5T", "4M"],
					snore: ["6T", "5T", "4T"],
					solarbeam: ["7M", "6M", "5M", "4M"],
					substitute: ["7M", "6M", "5M", "4M"],
					sunnyday: ["7M", "6M", "5M", "4M"],
					swagger: ["7M", "6M", "5M", "4M"],
					swift: ["4T"],
					tackle: ["7L1", "6L1", "5L1", "4L1"],
					thief: ["7M", "6M", "5M", "4M"],
					thunder: ["7M", "6M", "5M", "4M"],
					thunderbolt: ["7M", "6M", "5M", "4M"],
					thunderwave: ["7M", "6M", "5M", "4M"],
					toxic: ["7M", "6M", "5M", "4M"],
					triattack: ["7L50", "6L50", "5L51", "4L51"],
					trick: ["6T", "5T", "4T"],
					trickroom: ["7M", "7L1", "6M", "6L1", "5M", "5L1", "4M", "4L1"],
					uproar: ["6T", "5T", "4T"],
					wonderroom: ["5T"],
					zapcannon: ["7L62", "7L1", "6L1", "5L62", "4L62"],
					zenheadbutt: ["6T", "5T", "4T"],
				}
			},
	solosisistor: {
		learnset: {
		acid: ["7L7"],
		acidarmor: ["719"],
		acidspray: ["7L31"],
		astonish: ["7E"],
		attract: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		confuseray: ["7E"],
		doubleteam: ["7M"],
		dreameater: ["7M"],
		embargo: ["7M"],
		endeavor: ["7L28"],
		energyball: ["7M"],
		explosion: ["7M"],
		facade: ["7M"],
		flashcannon: ["7M"],
		frustration: ["7M"],
		futuresight: ["7LM"],
		gastroacid: ["7E"],
		gyroball: ["7M"],
		healblock: ["7L46"],
		hiddenpower: ["7M", "7L14"],
		imprison: ["7E"],
		infestation: ["7M"],
		lightscreen: ["7M", "7L16"],
		nightshade: ["7E"],
		nuclearray: ["7L48"],
		painsplit: ["7L33"],
		protect: ["7M"],
		psychic: ["7M", "7L37"],
		psychup: ["7M"],
		psyshock: ["7M", "7L25"],
		psywave: ["7L1"],
		raindance: ["7M"],
		recover: ["7L24"],
		reflect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		rocktomb: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7E"],
		shadowball: ["7M"],
		skillswap: ["7L40",],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		sludgewave: ["7M"],
		snatch: ["7L10"],
		snore: ["6T"],
		substitute: ["7M"],
		swagger: ["7M"],
		thunder: ["7M"],
		thunderwave: ["7M"],
		toxic: ["7M"],
		trick: ["7E"],
		trickroom: ["7M"],
		wonderroom: ["7E"],
	}},
	duosion: {learnset: {
		acid: ["7L7", "7L1"],
		acidarmor: ["7L19"],
		acidspray: ["7L31"],
		attract: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		doubleteam: ["7M"],
		dreameater: ["7M"],
		embargo: ["7M"],
		endeavor: ["7L28"],
		energyball: ["7M"],
		explosion: ["7M"],
		facade: ["7M"],
		flashcannon: ["7M"],
		frustration: ["7M"],
		futuresight: ["7E"],
		gyroball: ["7M"],
		healblock: ["7L50"],
		hiddenpower: ["7M", "7L14"],
		infestation: ["7M"],
		lightscreen: ["7M", "7L16"],
		nuclearray: ["7L53"],
		painsplit: ["7L34"],
		protect: ["7M"],
		psychic: ["7M", "7L39"],
		psychup: ["7M"],
		psyshock: ["7M", "7L25"],
		psywave: ["7L1"],
		raindance: ["7M"],
		recover: ["7L24"],
		reflect: ["7M", "7L3", "7L1"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		rocktomb: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		shadowball: ["7M"],
		skillswap: ["7L43"],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		sludgewave: ["7M"],
		snatch: ["7L10"],
		substitute: ["7M"],
		swagger: ["7M"],
		thunder: ["7M"],
		thunderwave: ["7M"],
		toxic: ["7M"],
		trickroom: ["7M"],
		wonderroom: ["7E"],
	}},
	reuniclus: {learnset: {
		acid: ["7L7", "7L1"],
		acidarmor: ["7L19"],
		acidspray: ["7L31"],
		attract: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		dizzypunch: ["7L1"],
		doubleteam: ["7M"],
		dreameater: ["7M"],
		embargo: ["7M"],
		endeavor: ["7L28"],
		energyball: ["7M"],
		explosion: ["7M"],
		facade: ["7M"],
		flashcannon: ["7M"],
		fling: ["7M"],
		focusblast: ["7M"],
		frustration: ["7M"],
		futuresight: ["7E"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		gyroball: ["7M"],
		healblock: ["7L54"],
		hiddenpower: ["7M", "7L14"],
		hyperbeam: ["7M"],
		infestation: ["7M"],
		lightscreen: ["7M", "7L16"],
		wonderroom: ["7E"],
		painsplit: ["7L34"],
		poisonjab: ["7M"],
		protect: ["7M"],
		psychic: ["7M", "7L39"],
		psychup: ["7M"],
		psyshock: ["7M", "7L25"],
		psywave: ["7L1"],
		raindance: ["7M"],
		recover: ["7L24"],
		reflect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		rocktomb: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		shadowball: ["7M"],
		skillswap: ["7L45"],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		sludgewave: ["7M"],
		snatch: ["7L10"],
		substitute: ["7M"],
		swagger: ["7M"],
		thunder: ["7M"],
		thunderwave: ["7M"],
		toxic: ["7M"],
		trickroom: ["7M"],
		wonderroom: ["7E"],
	}
	},
};
