'use strict';
exports.BattleItems = {
    "venusaurumz": {
        id: "venusaurumz",
        name: "Venusaurum-Z",
        onTakeItem: false,
        zMove: "Swampy Smackdown",
        zMoveFrom: "Energy Ball",
        zMoveUser: ["Venusaur"],
        desc: "If the holder is Venusaur with the move Energy Ball, it can use Swampy Smackdown.",
    },
    "charizardiumz": {
        id: "charizardiumz",
        name: "Charizardium-Z",
        onTakeItem: false,
        zMove: "Intensified Inferno",
        zMoveFrom: "Flamethrower",
        zMoveUser: ["Charizard"],
        desc: "If the holder is Charizard with the move Flamethrower, it can use Intensified Inferno.",
    },
    "blastoisiumz": {
        id: "blastoisiumz",
        name: "Blastoisium-Z",
        onTakeItem: false,
        zMove: "Destructive Downpour",
        zMoveFrom: "Scald",
        zMoveUser: ["Blastoise"],
        desc: "If the holder is Blastoise with the move Scald, it can use Destructive Downpour.",
    },
    "alolaninetaliumz": {
        id: "alolaninetaliumz",
        name: "Alolaninetalium-Z",
        onTakeItem: false,
        zMove: "Hail Hydra",
        zMoveFrom: "Blizzard",
        zMoveUser: ["Ninetales-Alola"],
        desc: "If the holder is Ninetales-Alola with the move Blizzard, it can use Hail Hydra.",
    },
    "tyraniumz": {
        id: "tyraniumz",
        name: "Tyranium-Z",
        onTakeItem: false,
        zMove: "Pursuing Strike",
        zMoveFrom: "Pursuit",
        zMoveUser: ["Tyranitar"],
        desc: "If the holder is Tyranitar with the move Pursuit, it can use Pursuing Strike.",
    },
    "hippowniumz": {
        id: "hippowniumz",
        name: "Hippownium-Z",
        onTakeItem: false,
        zMove: "Earthly Crush",
        zMoveFrom: "Earthquake",
        zMoveUser: ["Hippowdon"],
        desc: "If the holder is Hippowdon with the move Earthquake, it can use Earthly Crush.",
    },
    "abomasnowniumz": {
        id: "abomasnowniumz",
        name: "Abomasnownium-Z",
        onTakeItem: false,
        zMove: "Blossoming Life Drain",
        zMoveFrom: "Giga Drain",
        zMoveUser: ["Abomasnow"],
        desc: "If the holder is Abomasnow with the move Gig Drain, it can use Blossoming Life Drain.",
    },
    "gigaliumz": {
        id: "gigaliumz",
        name: "Gigalium-Z",
        onTakeItem: false,
        zMove: "Honing Rocks",
        zMoveFrom: "Rock Polish",
        zMoveUser: ["Gigalith"],
        desc: "If the holder is Gigalith with the move Rock Polish, it can use Honing Rocks.",
    },
    "vanilliumz": {
        id: "vanilliumz",
        name: "Vanillium-Z",
        onTakeItem: false,
        zMove: "Snowstorm Spinkle",
        zMoveFrom: "Blizzard",
        zMoveUser: ["Vanilluxe"],
        desc: "If the holder is Vanilluxe with the move Blizzard, it can use Snowstorm Spinkle.",
    },
    "ninetalesiumz": {
        id: "ninetalesiumz",
        name: "Ninetalesium-Z",
        onTakeItem: false,
        zMove: "Inferno Burst",
        zMoveFrom: "Fire Blast",
        zMoveUser: ["Ninetales"],
        desc: "If the holder is Ninetales with the move Fire Blast, it can use Inferno Burst.",
    },
    "groudoniumz": {
        id: "groudoniumz",
        name: "Groudonium-Z",
        onTakeItem: false,
        zMove: "Blitzing Tremor",
        zMoveFrom: "Precipice Blades",
        zMoveUser: ["Groudon"],
        desc: "If the holder is Groudon with the move Precipice Blades, it can use Blitzing Tremor.",
    },
     "torkoaliumz": {
        id: "torkoaliumz",
        name: "Torkoalium-Z",
        onTakeItem: false,
        zMove: "Pyrotechnics",
        zMoveFrom: "Heat Wave",
        zMoveUser: ["Torkoal"],
        desc: "If the holder is Torkoal with the move Heat Wave, it can use Pyrotechnics.",
    },
};
