'use strict';

exports.BattleLearnsets = {
	yddraig: { learnset: {
    inferno: ["7L1", "7L54"],
    outrage: ["7L1", "7L60"],
    tackle: ["7L1"],
    ember: ["7L1"],
    tailwhip: ["7L1"],
    twister: ["7L1"],
    endeavor: ["7L4"],
    defog: ["7L9"],
    headbutt: ["7L13"],
    aircutter: ["7L18"],
    dragonbreath: ["7L22"],
    roar: ["7L27"],
    flamecharge: ["7L31", "7M"],
    dragondance: ["7L36"],
    boomburst: ["7L40"],
    dragonrush: ["7L45"],
    doubleteam: ["7L49", "7M"],
    clangingscales: ["7E"],
    dragonpulse: ["7E"],
    wideguard: ["7E"],
    overheat: ["7E", "7M"],
    dracometeor: ["7T"],
    workup: ["7M"],
    dragonclaw: ["7M"],
    calmmind: ["7M"],
    roar: ["7M"],
    toxic: ["7M"],
    bulkup: ["7M"],
    hiddenpower: ["7M"],
    sunnyday: ["7M"],
    taunt: ["7M"],
    hyperbeam: ["7M"],
    lightscreen: ["7M"],
    protect: ["7M"],
    roost: ["7M"],
    safeguard: ["7M"],
    frustration: ["7M"],
    solarbeam: ["7M"],
    thunderbolt: ["7M"],
    thunder: ["7M"],
    return: ["7M"],
    brickbreak: ["7M"],
    reflect: ["7M"],
    flamethrower: ["7M"],
    fireblast: ["7M"],
    aerialace: ["7M"],
    torment: ["7M"],
    facade: ["7M"],
    rest: ["7M"],
    attract: ["7M"],
    round: ["7M"],
    echoedvoice: ["7M"],
    steelwing: ["7M"],
    roost: ["7M"],
    skydrop: ["7M"],
    brutalswing: ["7M"],
    acrobatics: ["7M"],
    shadowclaw: ["7M"],
    payback: ["7M"],
    gigaimpact: ["7M"],
    thunderwave: ["7M"],
    swordsdance: ["7M"],
    fly: ["7M"],
    bulldoze: ["7M"],
    dragontail: ["7M"],
    infestation: ["7M"],
    poisonjab: ["7M"],
    swagger: ["7M"],
    sleeptalk: ["7M"],
    uturn: ["7M"],
    substitute: ["7M"],
    wildcharge: ["7M"],
    snarl: ["7M"],
    naturepower: ["7M"],
    darkpulse: ["7M"],
    confide: ["7M"],
    }},
	detuoy: { learnset: {
		explosion: ["7L1"],
	}},
	
	doduo: {learnset: {
		acupressure: ["7L33”],
		aerialace: ["7M"],
		agility: ["7L26"],
		assurance: ["7E"],
		attract: ["7M"],
		bravebird: ["7E"],
		confide: ["7M"],
		doublehit: ["7L22"],
		doubleteam: ["7M"],
		drillpeck: ["7L43"],
		echoedvoice: ["7M"],
		endeavor: ["7L47", "7E"],
		facade: ["7M"],
		feintattack: ["7E"],
		flail: ["7E"],
		flashcannon: ["7M"],
		fly: ["7M"],
		frustration: ["7M"],
		furyattack: ["7L12"],
		growl: ["7L1"],
		hiddenpower: ["7M"],
		irondefense: ["7E"],
		ironhead: ["7E"],
		jumpkick: ["7L40"],
		mirrormove: ["7E"],
		naturalgift: ["7E"],
		peck: ["7L1"],
		pluck: ["7L19"],
		protect: ["7M"],
		pursuit: ["7L15"],
		quickattack: ["7L5"],
		rest: ["7M"],
		return: ["7M"],
		roost: ["7M"],
		round: ["7M"],
		sleeptalk: ["7M"],
		steelwing: ["7M", "7L9"],
		smartstrike: ["7M"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		swordsdance: ["7M", "7L36"],
		thief: ["7M"],
		impalingfeather: ["7L50"],
		toxic: ["7M"],
		heavyslam: ["7L29"],
		workup: ["7M"],
	}},
	dodrio: {learnset: {
		acupressure: ["7L34"],
		aerialace: ["7M"],
		agility: ["7L260"],
		assurance: ["7E"],
		attract: ["7M"],
		bravebird: ["7E"],
		confide: ["7M"],
		doublehit: ["7L22"],
		doubleteam: ["7M"],
		drillpeck: ["7L47"],
		echoedvoice: ["7M"],
		endeavor: ["7L52", "7E"],
		facade: ["7M"],
		feintattack: ["7E"],
		flail: ["7E"],
		flashcannon: ["7M"],
		fly: ["7M"],
		frustration: ["7M"],
		furyattack: ["7L121"],
		gigaimpact: ["7M"],
		growl: ["7L1"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		irondefense: ["7E"],
		ironhead: ["7E"],
		jumpkick: ["7L43"],
		mirrormove: ["7E"],
		naturalgift: ["7E"],
		payback: ["7M"],
		peck: ["7L1"],
		pluck: ["7L19"],
		protect: ["7M"],
		pursuit: ["7L15"],
		quickattack: ["7L5", "7E", "7L1"],
		rest: ["7M"],
		return: ["7M"],
		roost: ["7M"],
		round: ["7M"],
		sleeptalk: ["7M"],
		smartstrike: ["7M"],
		steelwing: ["7M", "7L8", “7L1”],
		substitute: ["7M"],
		sunnyday: ["7M"],
		supersonic: ["7E"],
		swagger: ["7M"],
		swordsdance: ["7M", "7L38"],
		taunt: ["7M"],
		thief: ["7M"],
		impalingfeather: ["7L56"],
		torment: ["7M"],
		toxic: ["7M"],
		triattack: ["7L1"],
		heavyslam: ["7L29"],
		workup: ["7M"],
	}},

  };
