exports.commands= {
'ei':function(target,room,user,connection, cmd,message)
	{
var by=user;
var arg=target;
		var abilities =
		{
			aerilate : 'Air Balloon',
			adaptability : 'Apicot Berry',
			adapt : 'Apicot Berry',
			analytic:'Water Gem',
			anticipation : 'Black Belt',
			arenatrap : 'Bug Gem',
			aromaveil : 'Black Glasses',
			aurabreak : 'Black Sludge',
			baddreams : 'BrightPowder',
			battlearmor : 'Cell Battery',
			bigpecks : 'Charcoal',
			blaze : 'Charti Berry',
			bulletproof : 'Chesto Berry',
			cheekpouch : 'Chilan Berry',
			chlorophyll : 'Chople Berry',
			clearbody : 'Coba Berry',
			cloudnine : 'Colbur Berry',
			colorchange : 'Custap Berry',
			competitive : 'Damp Rock',
			compoundeyes : 'Dragon Fang',
			contrary : 'Dark Gem',
			cursedbody : 'Eject Button',
			cutecharm : 'Expert Belt',
			damp : 'Flame Orb',
			darkaura : 'Focus Band',
			defeatist : 'Full Incense',
			defiant : 'Ganlon Berry',
			deltastream : 'Grepa Berry',
			desolateland : 'Grip Claw',
			desoland : 'Grip Claw',
			download : 'Haban Berry',
			drizzle : 'Hard Stone',
			drought : 'Heat Rock',
			dryskin : 'Iapapa Berry',
			earlybird : 'Icy Rock',
			effectspore : 'Kasib Berry',
			fairyaura : 'Kebia Berry',
			filter : 'Kee Berry',
			flamebody : 'Kelpsy Berry',
			flareboost : 'King\'s Rock',
			flashfire : 'Lagging Tail',
			flowergift : 'Lansat Berry',
			flowerveil : 'Lax Incense',
			forecast : 'Leppa Berry',
			forewarn : 'Liechi Berry',
			friendguard : 'Luminous Moss',
			frisk : 'Magnet',
			furcoat : 'Dragon Gem',
			fc : 'Dragon Gem',
			galewings : 'Maranga Berry',
			gw : 'Maranga Berry',
			gluttony : 'Metal Coat',
			gooey: 'Metronome',
			grasspelt : 'Micle Berry',
			guts: 'Miracle Seed',
			harvest : 'Muscle Band',
			healer : 'Mystic Water',
			heatproof : 'Never-Melt Ice',
			heavymetal : 'Occa Berry',
			honeygather : 'Odd Incense',
			hugepower : 'Electric Gem',
			hustle : 'Passho Berry',
			hydration : 'Payapa Berry',
			hypercutter : 'Petaya Berry',
			icebody : 'Poison Barb',
			illuminate : 'Quick Claw',
			illusion : 'Razor Claw',
			immunity : 'Razor Fang',
			imposter : 'Fairy Gem',
			infiltrator : 'Rindo Berry',
			innerfocus : 'Rock Incense',
			insomnia : 'Rose Incense',
			intimidate : 'Red Card',
			intim : 'Red Card',
			ironbarbs : 'Roseli Berry',
			ironfist : 'Safety Goggles',
			justified : 'Salac Berry',
			keeneye : 'Scope Lens',
			klutz : 'Sea Incense',
			leafguard : 'Sharp Beak',
			levitate : 'Nomel Berry',
			lightmetal : 'Shell Bell',
			lightningrod : 'Shuca Berry',
			limber : 'Silk Scarf',
			liquidooze : 'SilverPowder',
			mbounce : 'Smooth Rock',
			magicbounce : 'Smooth Rock',
			magicguard : 'Snowball',
			mguard : 'Snowball',
			magician : 'Soft Sand',
			magmaarmor : 'Spell Tag',
			magnetpull : 'Starf Berry',
			marvelscale : 'Sticky Barb',
			megalauncher : 'Tanga Berry',
			minus : 'TwistedSpoon',
			moldbreaker : 'Wacan Berry',
			moody : 'Wave Incense',
			motordrive : 'Weakness Policy',
			moxie : 'White Herb',
			multiscale : 'Wide Lens',
			multitype : 'Wise Glasses',
			mummy : 'Yache Berry',
			naturalcure : 'Zoom Lens',
			noguard : 'Adamant Orb',
			normalize : 'Burn Drive',
			oblivious : 'Chill Drive',
			overcoat : 'DeepSeaScale',
			overgrow : 'DeepSeaTooth',
			owntempo : 'Douse Drive',
			parentalbond : 'Fire Gem',
			pbond : 'Fire Gem',
			pickpocket : 'Light Ball',
			pickup : 'Lucky Punch',
			pixilate : 'Griseous Orb',
			plus : 'Lustrous Orb',
			poisonheal : 'Metal Powder',
			ph : 'Metal Powder',
			poisonpoint : 'Quick Powder',
			poisontouch : 'Shock Drive',
			prankster : 'Mail',
			prank : 'Soul Dew',
			pressure : 'Stick',
			primordialsea : 'Thick Club',
			primsea : 'Thick Club',
			protean : 'Aguav Berry',
			purepower : 'Ice Gem',
			quickfeet : 'Aspear Berry',
			raindish : 'Binding Band',
			rattled : 'Cheri Berry',
			reckless : 'Destiny Knot',
			refrigerate : 'Enigma Berry',
			fridge : 'Enigma Berry',
			regen : 'Figy Berry',
			regenerator : 'Figy Berry',
			rivalry : 'Float Stone',
			rockhead : 'Iron Ball',
			roughskin : 'Jaboca Berry',
			runaway : 'Macho Brace',
			sandforce : 'Mago Berry',
			sandrush : 'Oran Berry',
			sandstream : 'Pecha Berry',
			sandveil : 'Persim Berry',
			sapsipper : 'Rawst Berry',
			scrappy : 'Ring Target',
			serenegrace : 'Rowap Berry',
			serenevil : 'Rowap Berry',
			shadowtag : 'Poison Gem',
			shedskin : 'Wiki Berry',
			sheerforce : 'Armor Fossil',
			sf : 'Armor Fossil',
			shellarmor : 'Belue Berry',
			shielddust : 'Bluk Berry',
			simple : 'Psychic Gem',
			skilllink : 'Cherish Ball',
			slowstart : 'Claw Fossil',
			sniper : 'Cornn Berry',
			snowcloak : 'Cover Fossil',
			snowwarning : 'Dive Ball',
			solarpower : 'Dome Fossil',
			solidrock : 'Dream Ball',
			soundproof : 'Durin Berry',
			speedboost : 'Dusk Ball',
			stall : 'Electrizer',
			stancechange : 'Energy Powder',
			'static' : 'Fast Ball',
			steadfast : 'Freind Ball',
			stench : 'Great Ball',
			stickyhold : 'Heal Ball',
			stormdrain : 'Heavy Ball',
			strongjaw : 'Helix Fossil',
			sturdy : 'Hondew Berry',
			suctioncups : 'Level Ball',
			superluck : 'Love Ball',
			swarm : 'Lure Ball',
			sweetveil : 'Luxury Ball',
			swiftswim : 'Magost Berry',
			symbiosis : 'Master Ball',
			synchronize : 'Moon Ball',
			tangledfeet : 'Nanab Berry',
			technician : 'Nest Ball',
			tech : 'Nest Ball',
			telepathy : 'Net Ball',
			thickfat : 'Old Amber',
			tintedlens : 'Pamtre Berry',
			torrent : 'Park Ball',
			toughclaws : 'Pinap Berry',
			toxicboost : 'Plume Fossil',
			trace : 'Poke Ball',
			truant : 'Pomeg Berry',
			unaware : 'Qualot Berry',
			unburden : 'Quick Ball',
			unnerve : 'Rabuta Berry',
			victorystar : 'Rare Bone',
			vitalspirit : 'Razz Berry',
			voltabsorb : 'Repeat Ball',
			waterabsorb : 'Root Fossil',
			waterveil : 'Safari Ball',
			weakarmor : 'Skull Fossil',
			whitesmoke : 'Spelon Berry',
			wonderguard : 'Steel Gem',
			wg : 'Steel Gem',
			wonderskin : 'Sport Ball',
			zenmode : 'Tamato Berry',
			aftermath : 'Premier Ball'
		};
		var text = "";//this.hasRank(by, '+%@#&~') || room.charAt(0) === ',' ? '' : '/pm ' + by + ', ';
	        var rebuild = function(zom)
	        {
	        	var k="";
					for(var i=0;i<zom.length;i++)
					{
						if(zom.charAt(i)===' '||zom.charAt(i)==='-'||zom.charAt(i)==='.'||zom.charAt(i)==='/'||zom.charAt(i)==='+'||zom.charAt(i)==='['||zom.charAt(i)===']')
							continue;
						else
							k=k+zom.charAt(i);
					}
					//console.log(k);
					return k;
	        }
	        var abe = rebuild(arg.toLowerCase(arg));
	        if(!(this.cmdToken=='h'||this.cmdToken=='H'||this.cmdToken=='g')||this.cmdToken=='G')
	        {
	        if(arg=='')
	        	text+="Usage: ``.ei <Ability>``"
			else if(arg=='bans')
	        	text+="The current banlist for Enchanted Items is: Ubers, Kyurem-Black, Chatter, Shedinja, and the held abilities of Arena Trap, Contrary, Fur Coat, Huge Power, Imposter, Parental Bond, Pure Power, Shadow Tag, Simple, Trace(temporarily) and Wonder Guard.";
	        else if(arg=='retain')
	        	text+="These items retain their effects in EI: Assault Vest, Choice Band, Choice Scarf, Choice Specs, Eviolite, Focus Sash, Leftovers, Life Orb, Light Clay, Lum Berry, Mental Herb, Power Herb, Rocky Helmet, Sitrus Berry, Shed Shell, Toxic Orb, Mega Stones and Type Plates."
	        else if(arg=='turboblaze' || arg == 'teravolt')
	        	text+="Please use Mold Breaker instead of that ability, because it doesn't have an Enchanted Item anymore. The Enchanted Item for Mold Breaker is: Wacan Berry.";
	        else if(abilities[abe]==undefined)
	        	text+="Sorry, that ability does not exist."
	        else
	        	text+="The Enchanted Item for "+arg+" is "+abilities[abe]+".";
if (!this.runBroadcast()) return;
	        this.sendReply(text);
	        }
	  },
};
