'use strict';

exports.BattlePokedex = {
 	solsprite: {
	      	num: -999,
	      	species: "Solsprite",
	      	types: ["Fire", "Fairy"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100, atk: 70, def: 130, spa: 110, spd: 90, spe: 80},
	      	abilities: {0: "Serene Grace"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	sostormo: {
	      	num: -999,
	      	species: "Sostormo",
	      	types: ["Rock", "Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 119, atk: 92, def: 138, spa: 56, spd: 74, spe: 22},
	      	abilities: {0: "Mold Breaker"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	roadroach: {
	      	num: -999,
	      	species: "Roadroach",
	      	types: ["Bug", "Ground"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 46, atk: 91, def: 81, spa: 40, spd: 51, spe: 76},
	      	abilities: {0: "Safe Swap"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	skybleu: {
	      	num: -999,
	      	species: "Skybleu",
	      	types: ["Water", "Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 95, atk: 70, def: 90, spa: 135, spd: 85, spe: 120},
	      	abilities: {0: "Gale Wings", 1: "Drizzle", H: "No Guard"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	jawnado: {
	      	num: -999,
	      	species: "Jawnado",
	      	types: ["Water", "Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75, atk: 110, def: 55, spa: 75, spd: 70, spe: 105},
	      	abilities: {0: "Strong Jaw", H: "Aerilate"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	valkyrieti: {
	      	num: -999,
	      	species: "Valkyrieti",
	      	types: ["Ground", "Fairy"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100, atk: 65, def: 95, spa: 140, spd: 90, spe: 105},
	      	abilities: {0: "Levitate"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
	mechroarmancer: { /* blame xp */
	      	num: 999,
	      	species: "Mechroarmancer",
	      	types: ["Steel", "Dragon"], /* Spandan add Ghost type as well*/
		genderRatio: "N",
		baseStats: {hp: 85, atk: 120, def: 110, spa: 120, spd: 90, spe: 75},
	      	abilities: {0: "Tough Claws", 1: "Magic Guard", H: "Steelworker"},
	      	heightm: 100,
	      	weightkg: 100,
	      	color: "Red",
	      	eggGroups: ["Field"],
    	},
};
