'use strict';

exports.BattlePokedex = {

swampamar:{
  num:-62,
  species:"Swampamar",
  types:["Dark","Water"],
  genderRatio:{M:0.5,F:0.5},
  baseStats:{hp:103,atk:111,def:99,spa:86,spd:92,spe:76},
  abilities:{0:"Turnabout Torrent"},
  heightm:2,
  weightkg:75.5,
  color:"Blue",
  eggGroups:["Water 2"],
},
swampamarmega:{num:-62,species:"Swampamar-Mega",baseSpecies:"Swampamar",forme:"Mega",formeLetter:"M",types:["Dark","Water"],baseStats:{hp:103,atk:151,def:119,spa:96,spd:112,spe:86},abilities:{0:"Swift Swim"},heightm:2,weightkg:75.5,color:"Blue",eggGroups:["Water 2"],
},
gyarotic:{num:-63,species:"Gyarotic",types:["Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:105,atk:102,def:89,spa:90,spd:122,spe:91},abilities:{0:"Intimidating Scales"},heightm:2,weightkg:75.5,color:"Blue",eggGroups:["Water 2"],
},

gyaroticmega:{num:-63,species:"Gyarotic-Mega",baseSpecies:"Gyarotic",forme:"Mega",formeLetter:"M",types:["Water","Dark"],baseStats:{hp:105,atk:132,def:119,spa:100,spd:152,spe:91},abilities:{0:"Mold Breaker"},heightm:2,weightkg:75.5,color:"Blue",eggGroups:["Water 2"],
},

azuninja:{num:-64,species:"Azuninja",types:["Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:96,atk:82,def:83,spa:91,spd:85,spe:96},abilities:{0:"Huge Torrent"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Water 1"],
},

chandeform:{num:-65,species:"Chandeform",types:["Ghost","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:72,def:90,spa:117,spd:90,spe:85},abilities:{0:"Flash Weather"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Amorphous"],
},

mismatross:{num:-66,species:"Chandeform",types:["Electric","Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:97,def:80,spa:115,spd:102,spe:87},abilities:{0:"Levitate"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Amorphous"],
},

haxardos:{num:-67,species:"Chandeform",types:["Dragon","Rock"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:96,atk:166,def:85,spa:72,spd:70,spe:87},abilities:{0:"Intense Rivalry"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

pangleye:{num:-68,species:"Pangleye",types:["Fighting","Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:109,def:86,spa:77,spd:78,spe:64},abilities:{0:"Molded Stall"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

pangleyemega:{num:-68,species:"Pangleye-Mega",baseSpecies:"Pangleye-",forme:"Mega",formeLetter:"M",types:["Fighting","Dark"],baseStats:{hp:82,atk:119,def:136,spa:97,spd:128,spe:34},abilities:{0:"Magic Bounce"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

garchados:{num:-69,species:"Garchados",types:["Ground","Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:111,atk:137,def:97,spa:80,spd:102,spe:101},abilities:{0:"Intimidate Veil"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

garchadosmegax:{num:-69,species:"Garchados-Mega-X",baseSpecies:"Garchados",forme:"Mega",formeLetter:"M",types:["Ground","Water"],baseStats:{hp:111,atk:177,def:117,spa:120,spd:112,spe:91},abilities:{0:"Sand Force"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

garchadosmegay:{num:-69,species:"Garchados-Mega-Y",baseSpecies:"Garchados",forme:"Mega",formeLetter:"M",types:["Ground","Dark"],baseStats:{hp:111,atk:167,def:127,spa:90,spd:132,spe:101},abilities:{0:"Mold Breaker"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

wailcatty:{num:-70,species:"Wailcatty",types:["Ground","Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:130,atk:87,def:65,spa:82,spd:60,spe:75},abilities:{0:"Normal Veil"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

gargatr:{num:-71,species:"Gargatr",types:["Dragon", "Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:106,atk:127,def:107,spa:89,spd:94,spe:100},abilities:{0:"Torrent"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

gargatrmega:{num:-71,species:"Gargatr-Mega",baseSpecies:"Gargatr",forme:"Mega",formeLetter:"M",types:["Dragon","Water"],baseStats:{hp:106,atk:167,def:127,spa:129,spd:104,spe:90},abilities:{0:"Sand Force"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

dragon:{num:-72,species:"Dragon",types:["Dark", "Poison"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:88,atk:100,def:100,spa:121,spd:116,spe:81},abilities:{0:"Levipoison"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

hawlusharp:{num:-73,species:"Hawlusharp",types:["Fighting", "Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:81,atk:118,def:97,spa:77,spd:76,spe:104},abilities:{0:"Armor Cast"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

cofagreelix:{num:-74,species:"Cofagreelix",types:["Steel", "Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:76,atk:77,def:182,spa:85,spd:95,spe:40},abilities:{0:"Mummy Fortitude"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Mineral"],
},

cofagreelixmega:{num:-74,species:"Cofagreelix-Mega",baseSpecies:"Cofagreelix",forme:"Mega",formeLetter:"M",types:["Steel", "Ghost"],baseStats:{hp:76,atk:117,def:212,spa:85,spd:125,spe:40},abilities:{0:"Sand Force"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Mineral"],
},

joltlord:{num:-75,species:"Joltlord",types:["Electric", "Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:127,atk:87,def:62,spa:110,spd:80,spe:105},abilities:{0:"Oblivious Absorb"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

vespicor:{num:-76,species:"Vespicor",types:["Dark", "Poison"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:97,def:123,spa:72,spd:98,spe:77},abilities:{0:"Sand Pressure"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Bug"],
},

aggrodos:{num:-77,species:"Aggrodos",types:["Water", "Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:92,atk:127,def:139,spa:70,spd:90,spe:75},abilities:{0:"FEAR"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

aggrodosmegax:{num:-77,species:"Aggrodos-Mega-X",baseSpecies:"Aggrodos",forme:"Mega",formeLetter:"M",types:["Water", "Dark"],baseStats:{hp:92,atk:157,def:169,spa:80,spd:120,spe:75},abilities:{0:"Mold Breaker"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

aggrodosmegay:{num:-77,species:"Aggrodos-Mega-Y",baseSpecies:"Aggrodos",forme:"Mega",formeLetter:"M",types:["Water", "Steel"],baseStats:{hp:92,atk:157,def:189,spa:70,spd:110,spe:75},abilities:{0:"Filter"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

zorcanine:{num:-78,species:"Dragon",types:["Fire", "Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:85,atk:117,def:80,spa:120,spd:80,spe:110},abilities:{0:"Illusion"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

archedactyl:{num:-79,species:"Archedactyl",types:["Rock", "Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:132,def:75,spa:96,spd:80,spe:130},abilities:{0:"Aura of Failure"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Flying"],
},

archedactylmega:{num:-79,species:"Archedactyl-Mega",baseSpecies:"Archedactyl",forme:"Mega",formeLetter:"M",types:["Rock", "Flying"],baseStats:{hp:87,atk:162,def:95,spa:106,spd:100,spe:150},abilities:{0:"Tough Claws"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Flying"],
},

chesdon:{num:-80,species:"Dragon",types:["Dark", "Poison"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:108,atk:119,def:130,spa:81,spd:83,spe:65},abilities:{0:"Cactus Power"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

mamodrill:{num:-81,species:"Mamodrill",types:["Ground", "Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:120,atk:142,def:80,spa:70,spd:72,spe:94},abilities:{0:"Snow Force"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

heliodra:{num:-82,species:"Dragon",types:["Dragon", "Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:86,atk:87,def:71,spa:119,spd:132,spe:104},abilities:{0:"Sandy Skin"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

scyscor:{num:-83,species:"Scyscor",types:["Bug", "Ground"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:112,def:112,spa:60,spd:87,spe:110},abilities:{0:"Technicutter"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Bug"],
},

joltry:{num:-84,species:"Joltry",types:["Grass", "Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:92,def:70,spa:110,spd:87,spe:115},abilities:{0:"ChlroVolt"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

azumaloom:{num:-85,species:"Azumaloom",types:["Water", "Grass"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:90,atk:100,def:90,spa:70,spd:80,spe:70},abilities:{0:"Healing Fat"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Fairy"],
},

sawkape:{num:-86,species:"Sawkape",types:["Fire", "Fighting"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:85,atk:124,def:83,spa:77,spd:83,spe:106},abilities:{0:"Blazing Body"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

weasol:{num:-86,species:"Weasol",types:["Dark", "Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:140,def:77,spa:75,spd:87,spe:115},abilities:{0:"Pressure"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

weasolmega:{num:-86,species:"Weasol-Mega",baseSpecies:"Weasol",forme:"Mega",formeLetter:"M",types:["Dark", "Ice"],baseStats:{hp:82,atk:160,def:77,spa:115,spd:87,spe:155},abilities:{0:"Magic Bounce"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

tyranichomp:{num:-87,species:"Tyranichomp",types:["Rock", "Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:114,atk:142,def:112,spa:97,spd:102,spe:91},abilities:{0:"Sand Stream"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

tyranichompmegax:{num:-87,species:"Tyranichomp-Mega-X",baseSpecies:"Tyranichomp",forme:"Mega",formeLetter:"M",types:["Rock", "Dragon"],baseStats:{hp:114,atk:172,def:152,spa:97,spd:122,spe:101},abilities:{0:"Sand Stream"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

tyranichompmegay:{num:-87,species:"Tyranichomp-Mega-Y",baseSpecies:"Tyranichomp",forme:"Mega",formeLetter:"M",types:["Rock", "Dragon"],baseStats:{hp:114,atk:182,def:132,spa:137,spd:112,spe:81},abilities:{0:"Sand Force"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

railie:{num:-88,species:"Railie",types:["Ice", "Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:80,atk:95,def:77,spa:95,spd:90,spe:105},abilities:{0:"Static Storm"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Fairy"],
},

railiemega:{num:-88,species:"Railie-Mega",baseSpecies:"Railie",forme:"Mega",formeLetter:"M",types:["Ice", "Electric"],baseStats:{hp:80,atk:135,def:77,spa:135,spd:90,spe:125},abilities:{0:"Refigerate"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Fairy"],
},

charatos:{num:-89,species:"Charatos",types:["Fire","Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:97,atk:115,def:89,spa:95,spd:103,spe:101},abilities:{0:"Dreaded Flames"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

charatosmegay:{num:-89,species:"Charatos-Mega-Y",baseSpecies:"Charatos",forme:"Mega",formeLetter:"M",types:["Fire","Water"],baseStats:{hp:97,atk:135,def:89,spa:145,spd:133,spe:101},abilities:{0:"Drought"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

charatosmegax:{num:-89,species:"Charatos-Mega-X",baseSpecies:"Charatos",forme:"Mega",formeLetter:"M",types:["Fire","Dragon"],baseStats:{hp:97,atk:161,def:122,spa:116,spd:103,spe:101},abilities:{0:"Tough Claws"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

charatosmegaz:{num:-89,species:"Charatos-Mega-Z",baseSpecies:"Charatos",forme:"Mega",formeLetter:"M",types:["Fire","Dark"],baseStats:{hp:97,atk:145,def:119,spa:105,spd:133,spe:101},abilities:{0:"Mold Breaker"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Dragon"],
},

aggrosaur:{num:-90,species:"Aggrosaur",types:["Grass","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:85,atk:106,def:141,spa:90,spd:90,spe:75},abilities:{0:"Rocky Growth"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

aggrosaurmegax:{num:-90,species:"Aggrosaur-Mega-X",baseSpecies:"Aggrosaur",forme:"Mega",formeLetter:"M",types:["Grass","Steel"],baseStats:{hp:85,atk:124,def:181,spa:112,spd:110,spe:75},abilities:{0:"Thick Fat"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

aggrosaurmegay:{num:-90,species:"Aggrosaur-Mega-Y",baseSpecies:"Aggrosaur",forme:"Mega",formeLetter:"M",types:["Grass","Steel"],baseStats:{hp:85,atk:136,def:191,spa:90,spd:110,spe:75},abilities:{0:"Filter"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Monster"],
},

blastinja:{num:-91,species:"Blastinja",types:["Water","Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:90,atk:104,def:98,spa:109,spd:103,spe:115},abilities:{0:"Torrent"},heightm:2,weightkg:75.5,color:"Blue",eggGroups:["Water 1"],
},

blastinjamega:{num:-91,species:"Blastinja-Mega",baseSpecies:"Blastinja",forme:"Mega",formeLetter:"M",types:["Water","Dark"],baseStats:{hp:90,atk:124,def:118,spa:159,spd:113,spe:115},abilities:{0:"Mega Launcher"},heightm:2,weightkg:75.5,color:"Blue",eggGroups:["Water 1"],
},

skaria:{num:-92,species:"Skaria",types:["Steel","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:80,atk:85,def:125,spa:65,spd:97,spe:85},abilities:{0:"Pristine"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Flying"],
},

skariamega:{num:-92,species:"Skaria-Mega",baseSpecies:"Skaria",forme:"Mega",formeLetter:"M",types:["Steel","Fairy"],baseStats:{hp:80,atk:125,def:145,spa:105,spd:97,spe:85},abilities:{0:"Pixilate"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Flying"],
},

magmozam:{num:-93,species:"Magmozam",types:["Fire", "Psychic"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:82,def:66,spa:140,spd:105,spe:111},abilities:{0:"Inner Body"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

magmozammega:{num:-93,species:"Magmozam-Mega",baseSpecies:"Magmozam",forme:"Mega",formeLetter:"M",types:["Fire","Psychic"],baseStats:{hp:75,atk:82,def:86,spa:180,spd:105,spe:141},abilities:{0:"Trace"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Human-Like"],
},

glakiss:{num:-93,species:"Glakiss",types:["Fairy","Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:92,atk:75,def:97,spa:110,spd:107,spe:90},abilities:{0:"Serene Focus"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Fairy"],
},

glakissmega:{num:-93,species:"Glakiss-Mega",baseSpecies:"Glakiss",forme:"Mega",formeLetter:"M",types:["Fairy","Ice"],baseStats:{hp:92,atk:115,def:97,spa:150,spd:107,spe:110},abilities:{0:"Refigerate"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Fairy"],
},

sharpedos:{num:-94,species:"Sharpedos",types:["Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:92,atk:132,def:69,spa:87,spd:80,spe:98},abilities:{0:"Intimidating Fangs"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Water 1"],
},

sharpedosmegax:{num:-94,species:"Sharpedos-Mega-X",baseSpecies:"Sharpedos",forme:"Mega",formeLetter:"M",types:["Water"],baseStats:{hp:92,atk:152,def:99,spa:102,spd:105,spe:108},abilities:{0:"Strong Jaw"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Water 1"],
},

sharpedosmegay:{num:-94,species:"Sharpedos-Mega-Y",baseSpecies:"Sharpedos",forme:"Mega",formeLetter:"M",types:["Water","Dark"],baseStats:{hp:92,atk:162,def:99,spa:97,spd:110,spe:98},abilities:{0:"Mold Breaker"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Water 1"],
},

vapornine:{num:-95,species:"Vapornine",types:["Water","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:120,atk:97,def:80,spa:115,spd:97,spe:90},abilities:{0:"Intimidating Absorb"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

pidgetot:{num:-96,species:"Pidgetot",types:["Normal","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:89,atk:82,def:70,spa:91,spd:66,spe:106},abilities:{0:"Keen Feet"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Field"],
},

pidgetotmega:{num:-96,species:"Pidgetot-Mega",baseSpecies:"Pidgetot",forme:"Mega",formeLetter:"M",types:["Normal","Flying"],baseStats:{hp:89,atk:82,def:75,spa:156,spd:76,spe:126},abilities:{0:"No Guard"},heightm:2,weightkg:75.5,color:"Brown",eggGroups:["Flying"],
},
blasterain:{num:-128,species:"Blasterain",types:["Water","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:84,atk:81,def:91,spa:92,spd:103,spe:79},abilities:{0:"Sea Monster"},heightm:1.6,weightkg:85.5,color:"Blue",eggGroups:["Water1"],otherFormes:["blasterainmega"], 
 },
blasterainmega:{num:-128,species:"Blasterain-Mega",baseSpecies:"Blasterain",forme:"Mega",formeLetter:"M",types:["Water","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:84,atk:101,def:111,spa:142,spd:113,spe:79},abilities:{0:"Mega Launcher"},heightm:1.6,weightkg:111.1,color:"Blue",eggGroups:["Water1"], 
 },
entaria:{num:-129,species:"Entaria",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:110,def:100,spa:80,spd:90,spe:100},abilities:{0:"Under Pressure"},heightm:2.1,weightkg:198.0,color:"Red",eggGroups:["Undiscovered"],otherFormes:["entariamega"], 
 },
entariamega:{num:-129,species:"Entaria-Mega",baseSpecies:"Entaria",forme:"Mega",formeLetter:"M",types:["Fire","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:150,def:120,spa:120,spd:90,spe:100},abilities:{0:"Pixilate"},heightm:2.1,weightkg:198.0,color:"Red",eggGroups:["Undiscovered"], 
 },
krookz:{num:-130,species:"Krook-Z",types:["Normal","Ground"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:90,atk:98,def:70,spa:120,spd:72,spe:111},abilities:{0:"Cyber Criminal"},heightm:1.5,weightkg:96.3,color:"Red",eggGroups:["Undiscovered"], 
 },
mampharos:{num:-131,species:"Mampharos",types:["Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:90,def:87,spa:125,spd:90,spe:95},abilities:{0:"Static"},heightm:1.4,weightkg:61.5,color:"Yellow",eggGroups:["Field"],otherFormes:["mampharosmegam","mampharosmegaa"], 
 },
mampharosmegam:{num:-131,species:"Mampharos-Mega-M",baseSpecies:"Mampharos",forme:"Mega-M",formeLetter:"M",types:["Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:90,def:107,spa:155,spd:110,spe:125},abilities:{0:"Intimidate"},heightm:1.4,weightkg:61.5,color:"Yellow",eggGroups:["Field"], 
 },
mampharosmegaa:{num:-131,species:"Mampharos-Mega-A",baseSpecies:"Mampharos",forme:"Mega-A",formeLetter:"M",types:["Electric","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:110,def:107,spa:175,spd:110,spe:85},abilities:{0:"Mold Breaker"},heightm:1.4,weightkg:61.5,color:"Yellow",eggGroups:["Field"], 
 },
leafadon:{num:-132,species:"Leafadon",types:["Grass","Ground"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:96,atk:121,def:134,spa:74,spd:78,spe:66},abilities:{0:"Leaf Stream"},heightm:2,weightkg:300.0,color:"Green",eggGroups:["Field"], 
 },
shot:{num:-133,species:"Shot",types:["Grass","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:103,atk:100,def:75,spa:105,spd:75,spe:120},abilities:{0:"Serene Eyes"},heightm:1.5,weightkg:39.5,color:"Green",eggGroups:["Undiscovered"],otherFormes:["shotmega"], 
 },
shotmega:{num:-133,species:"Shot-Mega",baseSpecies:"Shot",forme:"Mega",formeLetter:"M",types:["Grass","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:103,atk:100,def:80,spa:170,spd:85,spe:140},abilities:{0:"No Guard"},heightm:1.5,weightkg:39.5,color:"Green",eggGroups:["Undiscovered"], 
 },
houdini:{num:-134,species:"Houdini",types:["Ghost","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:106,atk:85,def:93,spa:110,spd:108,spe:60},abilities:{0:"Hammer Space"},heightm:1.1,weightkg:31.0,color:"Red",eggGroups:["Undiscovered"],otherFormes:["houdinimega"], 
 },
houdinimega:{num:-134,species:"Houdini-Mega",baseSpecies:"Houdini",forme:"Mega",formeLetter:"M",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:106,atk:85,def:133,spa:130,spd:148,spe:60},abilities:{0:"Healer"},heightm:1.1,weightkg:31.0,color:"Red",eggGroups:["Undiscovered"], 
 },
pidgetran:{num:-135,species:"Pidgetran",types:["Fire","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:85,def:90,spa:120,spd:88,spe:109},abilities:{0:"Tangled Flames"},heightm:1.5,weightkg:31.8,color:"Red",eggGroups:["Undiscovered"],otherFormes:["pidgetranmega"], 
 },
pidgetranmega:{num:-135,species:"Pidgetran-Mega",baseSpecies:"Pidgetran",forme:"Mega",formeLetter:"M",types:["Fire","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:85,def:95,spa:185,spd:98,spe:129},abilities:{0:"No Guard"},heightm:1.5,weightkg:39.5,color:"Red",eggGroups:["Undiscovered"], 
 },
manatar:{num:-135,species:"Manatar",types:["Water","Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:117,def:105,spa:117,spd:100,spe:100},abilities:{0:"Hydro Stream"},heightm:2.0,weightkg:202.0,color:"Blue",eggGroups:["Undiscovered"],otherFormes:["manatarmega"], 
 },
manatarmega:{num:-136,species:"Manatar-Mega",baseSpecies:"Manatar",forme:"Mega",formeLetter:"M",types:["Water","Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:147,def:145,spa:117,spd:120,spe:110},abilities:{0:"Sand Stream"},heightm:2.0,weightkg:202.0,color:"Blue",eggGroups:["Undiscovered"], 
 },
aurortoise:{num:-137,species:"Aurortoise",types:["Water","Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:111,atk:90,def:96,spa:102,spd:108,spe:78},abilities:{0:"Hydrate"},heightm:1.6,weightkg:85.5,color:"Blue",eggGroups:["Monster"],otherFormes:["aurortoisemega"], 
 },
aurortoisemega:{num:-137,species:"Aurortoise-Mega",baseSpecies:"Aurortoise",forme:"Mega",formeLetter:"M",types:["Water","Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:111,atk:110,def:116,spa:152,spd:118,spe:78},abilities:{0:"Mega Launcher"},heightm:1.6,weightkg:85.5,color:"Blue",eggGroups:["Monster"], 
 },
metsir:{num:-138,species:"Metsir",types:["Steel","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:150,def:115,spa:75,spd:80,spe:97},abilities:{0:"Breaker"},heightm:1.6,weightkg:550.0,color:"Brown",eggGroups:["Undiscovered"],otherFormes:["metsirmegam","metsirmegap"], 
 },
metsirmegam:{num:-138,species:"Mestir-Mega-M",baseSpecies:"Metsir",forme:"Mega-M",formeLetter:"M",types:["Steel","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:160,def:135,spa:95,spd:100,spe:137},abilities:{0:"Tough Claws"},heightm:1.6,weightkg:550.0,color:"Brown",eggGroups:["Undiscovered"], 
 },
metsirmegap:{num:-138,species:"Metsir-Mega-P",baseSpecies:"Metsir",forme:"Mega-P",formeLetter:"M",types:["Steel","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:180,def:135,spa:85,spd:90,spe:117},abilities:{0:"Aerilate"},heightm:1.6,weightkg:550.0,color:"Brown",eggGroups:["Undiscovered"], 
 },
fablesteel:{num:-139,species:"Fablesteel",types:["Fairy","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:72,def:120,spa:103,spd:120,spe:55},abilities:{0:"Bodyguard"},heightm:1.3,weightkg:205.0,color:"Pink",eggGroups:["Undiscovered"], 
 },
bastioking:{num:-140,species:"Bastioking",types:["Water","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:88,atk:74,def:134,spa:84,spd:134,spe:40},abilities:{0:"Sturdy Tempo"},heightm:1.3,weightkg:149.5,color:"Red",eggGroup:["Monster"], 
 },
loppeye:{num:-141,species:"Loppeye",types:["Ghost","Norma"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:67,atk:85,def:89,spa:69,spd:91,spe:87},abilities:{0:"Late Bloomer"},heightm:1.6,weightkg:30.0,color:"Brown",eggGroups:["Human-Like"],otherFormes:["loppeyemegax","loppeyemegay"], 
 },
loppeyemegax:{num:-141,species:"Loppeye-Mega-X",baseSpecies:"Loppeye",forme:"Mega-X",formeLetter:"M",types:["Ghost","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:67,atk:95,def:139,spa:89,spd:141,spe:57},abilities:{0:"Magic Bounce"},heightm:1.6,weightkg:60.0,color:"Brown",eggGroups:["Human-Like"], 
 },
loppeyemegay:{num:-141,species:"Loppeye-Mega-Y",baseSpecies:"Loppeye",forme:"Mega-Y",formeLetter:"M",types:["Ghost","Fighting"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:67,atk:145,def:99,spa:69,spd:91,spe:117},abilities:{0:"Scrappy"},heightm:1.6,weightkg:60.0,color:"Brown",eggGroups:["Human-Like"], 
 },
houndlion:{num:-142,species:"Houndlion",types:["Dark","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:83,atk:90,def:98,spa:120,spd:76,spe:112},abilities:{0:"Justified Fire"},heightm:2.1,weightkg:250,color:"Black",eggGroups:["Undiscovered"],otherFormes:["houndlionmega"], 
 },
houndlionmega:{num:-142,species:"Houndlion-Mega",baseSpecies:"Houndlion",forme:"Mega",formeLetter:"M",types:["Dark","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:83,atk:90,def:138,spa:150,spd:86,spe:132},abilities:{0:"Solar Power"},heightm:2.1,weightkg:250,color:"Black",eggGroups:["Undiscovered"], 
 },
aegilene:{num:-143,species:"Aegilene",types:["Bug","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:65,atk:85,def:132,spa:85,spd:132,spe:99},abilities:{0:"Error Macro"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroup:["Undiscovered"],otherFormes:["aegileneblade"], 
 },
aegileneblade:{num:-143,species:"Aegilene-Blade",baseSpecies:"Aegilene",forme:"Blade",formeLetter:"B",types:["Bug","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:65,atk:132,def:85,spa:132,spd:85,spe:99},abilities:{0:"Error Macro"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroup:["Undiscovered"], 
 },
sablemimez:{num:-144,species:"Sablemimez",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:55,atk:70,def:80,spa:92,spd:102,spe:80},abilities:{0:"Slow 'n' Steady"},heightm:1.3,weightkg:54.5,color:"Pink",eggGroups:["Human-Like"],otherFormes:["sablemimezmega"], 
 },
sablemimezmega:{num:-144,species:"Sablemimez-Mega",baseSpecies:"Sablemimez",forme:"Mega",formeLetter:"M",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:55,atk:80,def:130,spa:112,spd:152,spe:50},abilities:{0:"Magic Bounce"},heightm:1.6,weightkg:60.0,color:"Pink",eggGroups:["Human-Like"], 
 },
casting:{num:-145,species:"Casting",types:["Poison","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:78,atk:90,def:105,spa:88,spd:80,spe:75},abilities:{0:"Monsoon"},heightm:1.2,weightkg:9.5,color:"White",eggGroup:["Amorphous"], 
 },
castingsunny:{num:-145,species:"Casting-Sunny",types:["Poison","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:78,atk:90,def:105,spa:88,spd:80,spe:75},abilities:{0:"Monsoon"},heightm:1.2,weightkg:9.5,color:"White",eggGroup:["Amorphous"], 
 },
castingrainy:{num:-145,species:"Casting-Rainy",types:["Poison","Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:78,atk:90,def:105,spa:88,spd:80,spe:75},abilities:{0:"Monsoon"},heightm:1.2,weightkg:9.5,color:"White",eggGroup:["Amorphous"], 
 },
castingicy:{num:-145,species:"Casting-Icy",types:["Poison","Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:78,atk:90,def:105,spa:88,spd:80,spe:75},abilities:{0:"Monsoon"},heightm:1.2,weightkg:9.5,color:"White",eggGroup:["Amorphous"], 
 },
swank:{num:-146,species:"Swank",types:["Water","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:85,atk:125,def:105,spa:80,spd:90,spe:101},abilities:{0:"Positive Growth"},heightm:1.5,weightkg:81.9,color:"Blue",eggGroups:["Undiscovered"],otherFormes:["swankmega"], 
 },
swankmega:{num:-146,species:"Swankz-Mega",baseSpecies:"Swank",forme:"Mega",formeLetter:"M",types:["Water","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:85,atk:165,def:125,spa:90,spd:110,spe:91},abilities:{0:"Swift Swim"},heightm:1.5,weightkg:90.0,color:"Blue",eggGroups:["Undiscovered"], 
 },
lucharma:{num:-147,species:"Lucharma",types:["Fighting","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:121,atk:116,def:77,spa:67,spd:71,spe:94},abilities:{0:"Pure Skill"},heightm:2.3,weightkg:238.5,color:"Red",eggGroup:["Human-Like"], 
 },
mana:{num:-148,species:"Mana",types:["Ghost","Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:92,def:80,spa:127,spd:95,spe:107},abilities:{0:"Magician's Wand"},heightm:1.5,weightkg:40.9,color:"Pink",eggGroups:["Undiscovered"],otherFormes:["manamega"], 
 },
manamega:{num:-148,species:"Mana-Mega",baseSpecies:"Mana",forme:"Mega",formeLetter:"M",types:["Ghost","Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:92,def:100,spa:157,spd:115,spe:137},abilities:{0:"Intimidate"},heightm:1.5,weightkg:90.0,color:"Pink",eggGroups:["Undiscovered"], 
 },
harem:{num:-149,species:"Harem",types:["Dragon","Ice"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:158,def:90,spa:110,spd:80,spe:101},abilities:{0:"Overwhelming Presence"},heightm:1.8,weightkg:105.5,color:"White",eggGroup:["Undiscovered"], 
 },
mismagivoir:{num:-150,species:"Mismagivoir",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:74,atk:72,def:72,spa:125,spd:120,spe:102},abilities:{0:"Synchrofloat"},heightm:1.6,weightkg:48.9,color:"Purple",eggGroups:["Amorphous"],otherFormes:["mismagivoirmega"], 
 },
mismagivoirmega:{num:-150,species:"Mismagivoir-Mega",baseSpecies:"Mismagivoir",forme:"Mega",formeLetter:"M",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:74,atk:92,def:92,spa:165,spd:140,spe:122},abilities:{0:"Pixilate"},heightm:1.6,weightkg:90.0,color:"Pink",eggGroups:["Amorphous"], 
 },
herasir:{num:-151,species:"Herasir",types:["Fighting","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:135,def:97,spa:57,spd:92,spe:95},abilities:{0:"Gut Breaker"},heightm:1.6,weightkg:60.0,color:"Blue",eggGroups:["Bug"],otherFormes:["herasirmegap","herasirmegam"], 
 },
herasirmegah:{num:-151,species:"Herasir-Mega-H",baseSpecies:"Herasir",forme:"Mega-H",formeLetter:"M",types:["Fighting","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:195,def:137,spa:57,spd:102,spe:85},abilities:{0:"Skill Link"},heightm:1.6,weightkg:70.0,color:"Blue",eggGroups:["Bug"], 
 },
herasirmegap:{num:-151,species:"Herasir-Mega-P",baseSpecies:"Herasir",forme:"Mega-P",formeLetter:"M",types:["Fighting","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:155,def:117,spa:67,spd:102,spe:115},abilities:{0:"Aerilate"},heightm:1.6,weightkg:60.0,color:"Blue",eggGroups:["Bug"], 
 },
banegross:{num:-152,species:"Banegross",types:["Steel","Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:135,def:97,spa:89,spd:86,spe:87},abilities:{0:"Hard Body"},heightm:1.6,weightkg:550.0,color:"Blue",eggGroups:["Undiscovered"],otherFormes:["banegrossmegax","banegrossmegay"], 
 },
banegrossmegax:{num:-152,species:"Banegross-Mega-X",baseSpecies:"Banegross",forme:"Mega-X",formeLetter:"M",types:["Steel","Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:145,def:117,spa:99,spd:106,spe:127},abilities:{0:"Tough Claws"},heightm:1.6,weightkg:550.0,color:"Blue",eggGroups:["Undiscovered"], 
 },
banegrossmegay:{num:-152,species:"Banegross-Mega-Y",baseSpecies:"Banegross",forme:"Mega-Y",formeLetter:"M",types:["Steel","Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:72,atk:185,def:107,spa:99,spd:106,spe:97},abilities:{0:"Prankster"},heightm:1.6,weightkg:550.0,color:"Blue",eggGroups:["Undiscovered"], 
 },
moltie:{num:-153,species:"Moltie",types:["Fairy","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:90,atk:100,def:120,spa:120,spd:120,spe:79},abilities:{0:"Calamity"},heightm:1.1,weightkg:100.5,color:"Red",eggGroup:["Undiscovered"], 
 },
grenheatja:{num:-154,species:"Grenheatja",types:["Water","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:81,atk:920,def:92,spa:126,spd:92,spe:119},abilities:{0:"Evaporation"},heightm:1.4,weightkg:50.5,color:"Red",eggGroup:["Undiscovered"], 
 },
dartios:{num:-155,species:"Dartios",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:130,def:70,spa:80,spd:85,spe:113},abilities:{0:"Sheer Flight"},heightm:2.0,weightkg:60.0,color:"Red",eggGroups:["Undiscovered"],otherFormes:["dartiosmega"], 
 },
dartiosmega:{num:-155,species:"Dartios-Mega",baseSpecies:"Dartios",forme:"Mega",formeLetter:"M",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:100,atk:170,def:90,spa:110,spd:95,spe:133},abilities:{0:"Levitate"},heightm:2.0,weightkg:80.0,color:"Red",eggGroups:["Undiscovered"], 
 },
metabat:{num:-156,species:"Metabat",types:["Steel","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:132,def:115,spa:82,spd:85,spe:110},abilities:{0:"Clear Focus"},heightm:1.8,weightkg:90.0,color:"Blue",eggGroups:["Undiscovered"],otherFormes:["metabatmega"], 
 },
metabatmega:{num:-156,species:"Metabat-Mega",baseSpecies:"Metabat",forme:"Mega",formeLetter:"M",types:["Steel","Flying"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:142,def:135,spa:92,spd:105,spe:150},abilities:{0:"Tough Claws"},heightm:2.0,weightkg:90.0,color:"Purple",eggGroups:["Undiscovered"], 
 },
jellivoir:{num:-157,species:"Jellivoir",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:94,atk:72,def:77,spa:115,spd:120,spe:80},abilities:{0:"Cursed Float"},heightm:1.6,weightkg:48.9,color:"Blue",eggGroups:["Amorphous"],otherFormes:["jellivoirmega"], 
 },
jellivoirmega:{num:-157,species:"Jellivoir-Mega",baseSpecies:"Jellivoir",forme:"Mega",formeLetter:"M",types:["Ghost","Fairy"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:94,atk:92,def:77,spa:155,spd:140,spe:100},abilities:{0:"Pixilate"},heightm:1.6,weightkg:90.0,color:"Blue",eggGroups:["Amorphous"], 
 },
suirizion:{num:-158,species:"Suirizion",types:["Grass","Water"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:104,atk:82,def:100,spa:110,spd:122,spe:100},abilities:{0:"Justice Power"},heightm:2.0,weightkg:200.0,color:"Blue",eggGroup:["Undiscovered"], 
 },
yangarde:{num:-159,species:"Yangarde",types:["Dragon","Bug"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:97,atk:111,def:118,spa:98,spd:85,spe:95},abilities:{0:"Speed Break"},heightm:5.0,weightkg:305.5,color:"Green",eggGroup:["Undiscovered"], 
 },
maladuck:{num:-160,species:"Maladuck",types:["Water","Dark"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:93,atk:97,def:93,spa:91,spd:87,spe:89},abilities:{0:"Atmospheric Pervesion"},heightm:1.5,weightkg:47.5,color:"Blue",eggGroup:["Water 1"], 
 },
hitmonklang:{num:-161,species:"Hitmonklang",types:["Steel","Fighitng"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:55,atk:115,def:110,spa:52,spd:105,spe:90},abilities:{0:"Electrotechnic"},heightm:1.5,weightkg:81.5,color:"Red",eggGroup:["Undiscovered"], 
 },
hazard:{num:-162,species:"Hazard",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:125,def:94,spa:94,spd:82,spe:108},abilities:{0:"Power-up Pinch"},heightm:1.8,weightkg:105.5,color:"Red",eggGroups:["Monster","Dragon"],otherFormes:["hazardmegax","hazardmegay"], 
 },
hazardmegax:{num:-162,species:"Hazard-Mega-X",baseSpecies:"Hazard",forme:"Mega-X",formeLetter:"M",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:171,def:127,spa:115,spd:82,spe:108},abilities:{0:"Tough Claws"},heightm:1.8,weightkg:105.5,color:"Red",eggGroups:["Monster","Dragon"], 
 },
hazardmegay:{num:-162,species:"Hazard-Mega-Y",baseSpecies:"Hazard",forme:"Mega-Y",formeLetter:"M",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:87,atk:145,def:94,spa:144,spd:112,spe:108},abilities:{0:"Drought"},heightm:1.8,weightkg:105.5,color:"Red",eggGroups:["Monster","Dragon"], 
 },
ferroslash:{num:-163,species:"Ferroslash",types:["Grass","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:77,atk:82,def:150,spa:62,spd:133,spe:50},abilities:{0:"Barb Stance"},heightm:1.5,weightkg:82.5,color:"Green",eggGroup:["Mineral"],otherFormes:["ferroslashblade"], 
 },
ferroslashblade:{num:-163,species:"Ferroslash-Blade",baseSpecies:"Ferroslash",forme:"Blade",formeLetter:"B",types:["Grass","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:77,atk:150,def:82,spa:133,spd:62,spe:50},abilities:{0:"Barb Stance"},heightm:1.5,weightkg:82.5,color:"Green",eggGroup:["Mineral"], 
 },
shaymizard:{num:-164,species:"Shaymizard",types:["Fire","Grass"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:89,atk:102,def:89,spa:114,spd:92,spe:120},abilities:{0:"Healing Blaze"},heightm:1.8,weightkg:105.5,color:"Green",eggGroups:["Undiscovered"],otherFormes:["shaymizardmegax","shaymizardmegay"], 
 },
shaymizardmegax:{num:-164,species:"Shaymizard-Mega-X",baseSpecies:"Shaymizard",forme:"Mega-X",formeLetter:"M",types:["Fire","Dragon"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:89,atk:148,def:122,spa:135,spd:92,spe:120},abilities:{0:"Tough Claws"},heightm:1.8,weightkg:105.5,color:"Green",eggGroups:["Undiscovered"], 
 },
shaymizardmegay:{num:-164,species:"Shaymizard-Mega-Y",baseSpecies:"Shaymizard",forme:"Mega-Y",formeLetter:"M",types:["Fire","Grass"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:89,atk:122,def:89,spa:164,spd:122,spe:120},abilities:{0:"Drought"},heightm:1.8,weightkg:105.5,color:"Green",eggGroups:["Undiscovered"], 
 },
hitachi:{num:-165,species:"Hitachi",types:["Steel","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:95,atk:95,def:113,spa:130,spd:113,spe:81},abilities:{0:"Serene Fire"},heightm:1.7,weightkg:430.5,color:"White",eggGroup:["Undiscovered"], 
 },
eek:{num:-166,species:"Eek",types:["Poison","Electric"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:105,atk:120,def:87,spa:95,spd:100,spe:60},abilities:{0:"Sticky Float"},heightm:2.1,weightkg:80.5,color:"Purple",eggGroup:["Amorphous"], 
 },
starchamp:{num:-167,species:"Starchamp",types:["Water","Fighitng"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:122,def:82,spa:82,spd:85,spe:105},abilities:{0:"Natural Guard"},heightm:1.1,weightkg:81.5,color:"Green",eggGroup:["Undiscovered"], 
 },
porylure:{num:-168,species:"Porylure",types:["Normal","Ghost"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:82,atk:67,def:82,spa:148,spd:82,spe:105},abilities:{0:"Flame Essence"},heightm:0.9,weightkg:34.5,color:"Purple",eggGroup:["Undiscovered"], 
 },
pidgemie:{num:-169,species:"Pidgemie",types:["Water","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:84,atk:77,def:80,spa:95,spd:80,spe:122},abilities:{0:"Natural Eye"},heightm:1.5,weightkg:39.5,color:"Blue",eggGroups:["Undiscovered"],otherFormes:["pidgemiemega"], 
 },
pidgemiemega:{num:-169,species:"Pidgemie-Mega",baseSpecies:"Pidgemie",forme:"Mega",formeLetter:"M",types:["Water","Normal"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:84,atk:77,def:85,spa:160,spd:90,spe:142},abilities:{0:"No Guard"},heightm:1.5,weightkg:39.5,color:"Blue",eggGroups:["Undiscovered"], 
 },
klazor:{num:-170,species:"Klazor",types:["Bug","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:105,def:100,spa:82,spd:85,spe:61},abilities:{0:"Math Surge"},heightm:1.8,weightkg:117.5,color:"Red",eggGroups:["Undiscovered"],otherFormes:["klazormega"], 
 },
klazormega:{num:-170,species:"Klazor-Mega",baseSpecies:"Klazor",forme:"Mega",formeLetter:"M",types:["Bug","Steel"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:75,atk:125,def:140,spa:92,spd:105,spe:71},abilities:{0:"Technician"},heightm:1.8,weightkg:117.5,color:"Red",eggGroups:["Undiscovered"], 
 },
gorecanion:{num:-171,species:"Gorecanion",types:["Water","Fire"],genderRatio:{M:0.5,F:0.5},baseStats:{hp:67,atk:97,def:112,spa:140,spd:90,spe:75},abilities:{0:"Swift Absorb"},heightm:1.7,weightkg:190.5,color:"Pink",eggGroup:["Undiscovered"], 
 },
perwearalola: {
num:-172,
species: "Perwear-Alola",
types: ["Dark", "Fighting"],
genderRatio: {M: 90.0, F: 10.0},
baseStats: {hp: 102, atk: 102, def: 80, spa: 75, spd: 72, spe: 97},
abilities: {0: "Fluffy Fur"},
heightm: 1.75,
weightkg: 65.0,
color: "Black",
eggGroups: ["Field"], 
},
crematoria:{
num: -173,
species: "Crematoria",
types: ["Flying", "Psychic"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 81, def: 78, spa: 139, spd: 107, spe: 100},
abilities: {0: "Ashes To Ashes"},
heightm: 1.70,
weightkg: 96.5,
color: "Orange",
eggGroups: ["Undiscovered"], 
},
cremetoriamegax: {
num:-173,
species: "Crematoria-Mega X",
baseSpecies: "Crematoria",
forme: "Mega",
formeLetter: "X",
types: ["Flying", "Dragon"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 127, def: 111, spa: 160, spd: 107, spe: 100},
abilities: {0: "Tough Claws"},
heightm: 1.7,
weightkg: 117,
color: "Black",
eggGroups: ["Undiscovered"],
},

crematoriamegay: {
 num: -173,
species: "Crematoria-Mega Y",
baseSpecies: "Crematoria",
forme: "Mega",
formeLetter: "Y",
types: ["Flying", "Psychic"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 101, def: 78, spa: 189, spd: 137, spe: 100},
abilities: {0: "Drought"},
heightm: 1.7,
weightkg: 107,
color: "Orange",
eggGroups: ["Undiscovered"],
},

crematoriasematary: {
num: -174,
species: "Crematoria-Sematary",
types: ["Flying", "Fighting"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 139, def: 100, spa: 81, spd: 78, spe: 107},
abilities: {0: "Ashes To Ashes"},
heightm: 1.70,
weightkg: 96.5,
color: "Orange",
eggGroups: ["Undiscovered"], 
},

crematoriasematarymegax: {
num: -174,
species: "Crematoria-Sematary Mega X",
baseSpecies: "Crematoria-Sematary",
forme: "Mega",
formeLetter: "X",
types: ["Flying", "Dragon"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 185, def: 133, spa: 102, spd: 78, spe: 107},
abilities: {0: "Tough Claws"},
heightm: 1.7,
weightkg: 117,
color: "Black",
eggGroups: ["Undiscovered"],
},

crematoriasematarymegay: {
num: -175,
species: "Crematoria-Sematary-Mega Y",
baseSpecies: "Crematoria-Sematary",
forme: "Mega",
formeLetter: "Y",
types: ["Flying", "Fighting"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 104, atk: 159, def: 100, spa: 131, spd: 108, spe: 107},
abilities: {0: "Drought"},
heightm: 1.7,
weightkg: 107,
color: "Orange",
eggGroups: ["Undiscovered"],
},
golisotop: { num: -176, species: "Golisotops", types: ["Bug", "Water"], genderRatio: {M: 5.0, F: 5.0}, baseStats: {hp: 77, atk: 130, def: 132, spa: 72, spd: 90, spe: 70}, abilities: {0: "Swift Retreat"}, heightm: 1.65, weightkg: 74.25, color: "Grey", eggGroups: ["Water 3"], },

lycanpae: { 
num: -177,
species: "Lycanape",
types: ["Rock", "Fighting"],
genderRatio: {M: 87.5, F: 12.5},
baseStats: {hp: 85, atk: 119, def: 78, spa: 89, spd: 78, spe: 120},
abilities: {0: "Blaze Rush"},
heightm: 1.0,
weightkg: 40.0,
color: "Brown",
eggGroups: ["Field"], 
},
pherothron:  { 
 num: -178,
 species: "Pherothorn",
types: ["Bug", "Steel"],
genderRatio: {M: 50.0, F: 50.0},
baseStats: {hp: 72, atk: 115, def: 94, spa: 95, spd: 96, spe: 95},
abilities: {0: "Beast Barbs"},
heightm: 1.4,
weightkg: 67.5,
color: "Grey",
eggGroups: ["Undiscovered"], 
},
 slampa: { 
  num: -179,
   species: "Slampa",
types: ["Water", "Dragon"],
genderRatio: {M: 60.0, F: 40.0},
baseStats: {hp: 96, atk: 77, def: 107, spa: 127, spd: 95, spe: 43},
abilities: {0: "Outrageous"},
heightm: 2.3,
weightkg: 131.75,
color: "Pink",
eggGroups: ["Monster"], 
 },
  slampamega: {
        num:-179,
        species: "Slampa-Mega",
        baseSpecies: "Slampa",
        forme: "Mega",
        formeLetter: "M",
        types: ["Water", "Dragon"],
        genderRatio: {M: 0.60 , F: 0.40},
        baseStats: {hp: 96, atk: 77, def: 177, spa: 157, spd: 95, spe: 43},
        abilities: {0: "Shell Armor"},
        heightm: 2.3,
        weightkg: 163.25,
        color: "Pink",
        eggGroups: ["Monster", ],
    },
};
